/*
 * Do not edit directly, this file was auto-generated.
 *
 * Los tokens de `tokens/component/email.json`, resueltos y en píxeles
 * absolutos. Un correo no puede leer una custom property (Outlook no
 * resuelve `var()`) ni entiende `rem`, así que sus valores tienen que
 * llegar así: como datos, listos para ir inline.
 */
export const emailTokens = {
  '--email-max-width': '600px',
  '--email-font-family': '"Google Sans Flex", system-ui, sans-serif',
  '--email-font-size': '20px',
  '--email-font-weight': '300',
  '--email-font-weight-range': '1 1000',
  '--email-line-height': '1.5',
  '--email-border-width': '1px',
  '--email-canvas-padding-block': '24px',
  '--email-canvas-padding-inline': '12px',
  '--email-padding-block': '24px',
  '--email-padding-inline': '24px',
  '--email-brand-padding-block': '16px',
  '--email-brand-padding-inline': '16px',
  '--email-opt-out-margin-block-start': '16px',
  '--email-heading-font-size': '32px',
  '--email-heading-font-weight': '500',
  '--email-heading-line-height': '1.1',
  '--email-heading-margin-block-end': '12px',
  '--email-text-margin-block-end': '16px',
  '--email-note-font-size': '16px',
  '--email-note-line-height': '1.65',
  '--email-text-emphasis-font-weight': '500',
  '--email-section-title-font-size': '24px',
  '--email-section-title-font-weight': '500',
  '--email-section-title-line-height': '1.3',
  '--email-section-title-margin-block-start': '24px',
  '--email-section-title-margin-block-end': '12px',
  '--email-section-title-color': '#111e30',
  '--email-list-margin-block-end': '16px',
  '--email-list-padding-inline-start': '24px',
  '--email-list-item-margin-block-end': '8px',
  '--email-quote-border-width': '2px',
  '--email-quote-border-color': '#4a4a4a',
  '--email-quote-padding-inline-start': '12px',
  '--email-quote-margin-block-end': '16px',
  '--email-callout-padding-block': '16px',
  '--email-callout-padding-inline': '16px',
  '--email-callout-margin-block-end': '16px',
  '--email-columns-margin-block-end': '16px',
  '--email-column-gutter': '16px',
  '--email-divider-width': '1px',
  '--email-divider-color': '#d0d0d0',
  '--email-divider-margin-block': '24px',
  '--email-key-value-margin-block-end': '12px',
  '--email-key-value-label-font-size': '16px',
  '--email-key-value-label-font-weight': '500',
  '--email-key-value-label-color': '#4a4a4a',
  '--email-code-font-family': '"Google Sans Code", ui-monospace, monospace',
  '--email-code-font-size': '16px',
  '--email-code-bg': '#f2f2f2',
  '--email-code-color': '#111e30',
  '--email-code-padding-block': '12px',
  '--email-code-padding-inline': '12px',
  '--email-code-margin-block-end': '16px',
  '--email-tag-font-size': '16px',
  '--email-tag-font-weight': '500',
  '--email-tag-border-radius': '9999px',
  '--email-tag-padding-block': '4px',
  '--email-tag-padding-inline': '12px',
  '--email-tag-margin-block-end': '16px',
  '--email-tone-info-bg': '#111e30',
  '--email-tone-info-color': '#ffffff',
  '--email-tone-success-bg': '#006616',
  '--email-tone-success-color': '#ffffff',
  '--email-tone-warning-bg': '#ffcd00',
  '--email-tone-warning-color': '#111e30',
  '--email-tone-error-bg': '#b30000',
  '--email-tone-error-color': '#ffffff',
  '--email-button-bg': '#baabff',
  '--email-button-color': '#111e30',
  '--email-button-hover-bg': '#ffcd00',
  '--email-button-hover-color': '#111e30',
  '--email-button-font-size': '20px',
  '--email-button-font-weight': '300',
  '--email-button-padding-block': '16px',
  '--email-button-width': '100%',
  '--email-button-fallback-margin-block-start': '12px',
  '--email-button-margin-block-end': '24px',
  '--email-logo-mark-size': '48px',
  '--email-logo-padding': '8px',
  '--email-canvas-bg': '#ffffff',
  '--email-bg': '#ffffff',
  '--email-color': '#111e30',
  '--email-muted-color': '#4a4a4a',
  '--email-border-color': '#111e30',
} as const;

export type EmailTokenName = keyof typeof emailTokens;
