// Do not edit directly, this file was auto-generated by Style Dictionary (sd.config.mjs). Run `pnpm build:tokens`.

import SwiftUI

/// Colores primitivos, de marca y rellenos universales: el mismo valor en superficie clara y oscura.
public enum BrandColors {
    /// Token `color.primary` — Primary brand color — used ~50% of the time
    public static let primary: Color = Color(brandHex: 0x111E30)
    /// Token `color.accent-1` — Accent 1 brand color — used ~20% of the time
    public static let accent1: Color = Color(brandHex: 0xBAABFF)
    /// Token `color.accent-2` — Accent 2 brand color — used ~20% of the time
    public static let accent2: Color = Color(brandHex: 0xFFCD00)
    /// Token `color.support-1` — Support 1 brand color — used ~5% of the time
    public static let support1: Color = Color(brandHex: 0x20E38E)
    /// Token `color.support-2` — Support 2 brand color — used ~5% of the time
    public static let support2: Color = Color(brandHex: 0xF05E1C)
    /// Token `color.error-fill` — Error — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto
    public static let errorFill: Color = Color(brandHex: 0xB30000)
    /// Token `color.error-fill-text` — Error — contenido sobre error-fill
    public static let errorFillText: Color = Color(brandHex: 0xFFFFFF)
    /// Token `color.success-fill` — Success — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto
    public static let successFill: Color = Color(brandHex: 0x006616)
    /// Token `color.success-fill-text` — Success — contenido sobre success-fill
    public static let successFillText: Color = Color(brandHex: 0xFFFFFF)
    /// Token `color.warning-fill` — Aviso — fondo sólido universal (igual en superficie clara y oscura). El amarillo de marca, aquí como rol de feedback. Nunca como color de texto
    public static let warningFill: Color = Color(brandHex: 0xFFCD00)
    /// Token `color.warning-fill-text` — Aviso — contenido sobre warning-fill: el prusia (11,17:1, AAA). El rol solo tiene estos dos tokens, a propósito: ver Foundations › Colores
    public static let warningFillText: Color = Color(brandHex: 0x111E30)
    /// Token `color.destructive-fill` — Destructive — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto
    public static let destructiveFill: Color = Color(brandHex: 0xB30000)
    /// Token `color.destructive-fill-text` — Destructive — contenido sobre destructive-fill
    public static let destructiveFillText: Color = Color(brandHex: 0xFFFFFF)
    /// Token `color.white` — Pure white
    public static let white: Color = Color(brandHex: 0xFFFFFF)
    /// Token `color.black` — Pure black
    public static let black: Color = Color(brandHex: 0x000000)
    /// Token `color.grey-lightest` — Superficie clara secundaria: bloque de código, kbd, burbujas, pie de tabla. Encima, texto prusia o grey-darkest
    public static let greyLightest: Color = Color(brandHex: 0xF2F2F2)
    /// Token `color.grey-light` — Bordes, dividers, separadores
    public static let greyLight: Color = Color(brandHex: 0xD0D0D0)
    /// Token `color.grey-dark` — Iconos de acción secundarios y controles deshabilitados. No es un gris de texto: todo texto va en prusia o grey-darkest
    public static let greyDark: Color = Color(brandHex: 0x6B6B6B)
    /// Token `color.grey-darkest` — Texto secundario y placeholder en superficie clara (AAA sobre blanco)
    public static let greyDarkest: Color = Color(brandHex: 0x4A4A4A)
    /// Token `color.prussian` — Brand prussian
    public static let prussian: Color = Color(brandHex: 0x111E30)
    /// Token `color.lavender` — Brand lavender
    public static let lavender: Color = Color(brandHex: 0xBAABFF)
    /// Token `color.yellow` — Brand yellow
    public static let yellow: Color = Color(brandHex: 0xFFCD00)
    /// Token `color.emerald` — Brand emerald
    public static let emerald: Color = Color(brandHex: 0x20E38E)
    /// Token `color.cayenne` — Brand cayenne
    public static let cayenne: Color = Color(brandHex: 0xF05E1C)
    /// Token `color.red` — System red — base (AAA sobre blanco; fill universal de error/destructive)
    public static let red: Color = Color(brandHex: 0xB30000)
    /// Token `color.red-light` — System red light — SOLO texto/icono/borde sobre prussian, nunca como fondo
    public static let redLight: Color = Color(brandHex: 0xFF8585)
    /// Token `color.green` — System green — base (AAA sobre blanco; fill universal de success)
    public static let green: Color = Color(brandHex: 0x006616)
    /// Token `color.green-light` — System green light — SOLO texto/icono/borde sobre prussian, nunca como fondo
    public static let greenLight: Color = Color(brandHex: 0x00CC2C)
}

/// Roles de color: cada uno es un `Color` dinámico que resuelve su valor claro u oscuro según el esquema.
public enum BrandColorRoles {
    /// Rol claro/oscuro. Tokens `color.error-text-on-light` / `color.error-text-on-dark`.
    public static let errorText = Color(brandLight: Color(brandHex: 0xB30000), dark: Color(brandHex: 0xFF8585))
    /// Rol claro/oscuro. Tokens `color.success-text-on-light` / `color.success-text-on-dark`.
    public static let successText = Color(brandLight: Color(brandHex: 0x006616), dark: Color(brandHex: 0x00CC2C))
    /// Rol claro/oscuro. Tokens `color.destructive-text-on-light` / `color.destructive-text-on-dark`.
    public static let destructiveText = Color(brandLight: Color(brandHex: 0xB30000), dark: Color(brandHex: 0xFF8585))
    /// Rol claro/oscuro. Tokens `color.text.on-light` / `color.text.on-dark`.
    public static let text = Color(brandLight: Color(brandHex: 0x111E30), dark: Color(brandHex: 0xFFFFFF))
    /// Rol claro/oscuro. Tokens `color.text.placeholder-on-light` / `color.text.placeholder-on-dark`.
    public static let textPlaceholder = Color(brandLight: Color(brandHex: 0x4A4A4A), dark: Color(brandHex: 0xD0D0D0))
    /// Rol claro/oscuro. Tokens `color.text.muted-on-light` / `color.text.muted-on-dark`.
    public static let textMuted = Color(brandLight: Color(brandHex: 0x4A4A4A), dark: Color(brandHex: 0xD0D0D0))
    /// Rol claro/oscuro. Tokens `color.background.light` / `color.background.dark`.
    public static let background = Color(brandLight: Color(brandHex: 0xFFFFFF), dark: Color(brandHex: 0x111E30))
    /// Rol claro/oscuro. Tokens `color.surface.secondary-on-light` / `color.surface.secondary-on-dark`.
    public static let surfaceSecondary = Color(brandLight: Color(brandHex: 0xF2F2F2), dark: Color(brandHex: 0x4A4A4A))
    /// Rol claro/oscuro. Tokens `color.surface.inverse-on-light` / `color.surface.inverse-on-dark`.
    public static let surfaceInverse = Color(brandLight: Color(brandHex: 0x4A4A4A), dark: Color(brandHex: 0xF2F2F2))
    /// Rol claro/oscuro. Tokens `color.surface.highlight-on-dark`. El token solo define el lado oscuro; en el otro lado vale lo mismo.
    public static let surfaceHighlight = Color(brandLight: Color(brandHex: 0x6B6B6B), dark: Color(brandHex: 0x6B6B6B))
    /// Rol claro/oscuro. Tokens `color.border.default-on-light`. El token solo define el lado claro; en el otro lado vale lo mismo.
    public static let borderDefault = Color(brandLight: Color(brandHex: 0xD0D0D0), dark: Color(brandHex: 0xD0D0D0))
    /// Rol claro/oscuro. Tokens `color.border.recessive-on-dark`. El token solo define el lado oscuro; en el otro lado vale lo mismo.
    public static let borderRecessive = Color(brandLight: Color(brandHex: 0x4A4A4A), dark: Color(brandHex: 0x4A4A4A))
    /// Rol claro/oscuro. Tokens `color.disabled.bg-on-light` / `color.disabled.bg-on-dark`.
    public static let disabledBg = Color(brandLight: Color(brandHex: 0xF2F2F2), dark: Color(brandHex: 0x4A4A4A))
    /// Rol claro/oscuro. Tokens `color.disabled.text-on-light` / `color.disabled.text-on-dark`.
    public static let disabledText = Color(brandLight: Color(brandHex: 0x4A4A4A), dark: Color(brandHex: 0xD0D0D0))
    /// Rol claro/oscuro. Tokens `color.disabled.border-on-light` / `color.disabled.border-on-dark`.
    public static let disabledBorder = Color(brandLight: Color(brandHex: 0xD0D0D0), dark: Color(brandHex: 0x6B6B6B))
    /// Rol claro/oscuro. Tokens `color.icon.secondary-on-light` / `color.icon.secondary-on-dark`.
    public static let iconSecondary = Color(brandLight: Color(brandHex: 0x6B6B6B), dark: Color(brandHex: 0xD0D0D0))
    /// Rol claro/oscuro. Tokens `color.chart.series-1` / `color.chart.series-1-on-dark`.
    public static let chartSeries1 = Color(brandLight: Color(brandHex: 0x1E7FF6), dark: Color(brandHex: 0x1D7CF0))
    /// Rol claro/oscuro. Tokens `color.chart.series-2` / `color.chart.series-2-on-dark`.
    public static let chartSeries2 = Color(brandLight: Color(brandHex: 0xF16123), dark: Color(brandHex: 0xED5F22))
    /// Rol claro/oscuro. Tokens `color.chart.series-3` / `color.chart.series-3-on-dark`.
    public static let chartSeries3 = Color(brandLight: Color(brandHex: 0x27A0AF), dark: Color(brandHex: 0x28A4B2))
    /// Rol claro/oscuro. Tokens `color.chart.series-4` / `color.chart.series-4-on-dark`.
    public static let chartSeries4 = Color(brandLight: Color(brandHex: 0xB29124), dark: Color(brandHex: 0x93771C))
    /// Rol claro/oscuro. Tokens `color.chart.series-5` / `color.chart.series-5-on-dark`.
    public static let chartSeries5 = Color(brandLight: Color(brandHex: 0xC62C90), dark: Color(brandHex: 0xD840A0))
    /// Rol claro/oscuro. Tokens `color.chart.series-6` / `color.chart.series-6-on-dark`.
    public static let chartSeries6 = Color(brandLight: Color(brandHex: 0x7D9D22), dark: Color(brandHex: 0x7FA123))
    /// Rol claro/oscuro. Tokens `color.chart.series-7` / `color.chart.series-7-on-dark`.
    public static let chartSeries7 = Color(brandLight: Color(brandHex: 0x6332C4), dark: Color(brandHex: 0x875EF0))
    /// Rol claro/oscuro. Tokens `color.chart.series-8` / `color.chart.series-8-on-dark`.
    public static let chartSeries8 = Color(brandLight: Color(brandHex: 0x28A86B), dark: Color(brandHex: 0x29AC6D))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-100` / `color.chart.sequential-100-on-dark`.
    public static let chartSequential100 = Color(brandLight: Color(brandHex: 0xDCE9FC), dark: Color(brandHex: 0x0E376B))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-200` / `color.chart.sequential-200-on-dark`.
    public static let chartSequential200 = Color(brandLight: Color(brandHex: 0xB6D2F8), dark: Color(brandHex: 0x164B90))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-300` / `color.chart.sequential-300-on-dark`.
    public static let chartSequential300 = Color(brandLight: Color(brandHex: 0x8FBAF5), dark: Color(brandHex: 0x1F61B6))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-400` / `color.chart.sequential-400-on-dark`.
    public static let chartSequential400 = Color(brandLight: Color(brandHex: 0x67A1F1), dark: Color(brandHex: 0x2978DE))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-500` / `color.chart.sequential-500-on-dark`.
    public static let chartSequential500 = Color(brandLight: Color(brandHex: 0x3B88EE), dark: Color(brandHex: 0x4E92EF))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-600` / `color.chart.sequential-600-on-dark`.
    public static let chartSequential600 = Color(brandLight: Color(brandHex: 0x236AC5), dark: Color(brandHex: 0x80B0F3))
    /// Rol claro/oscuro. Tokens `color.chart.sequential-700` / `color.chart.sequential-700-on-dark`.
    public static let chartSequential700 = Color(brandLight: Color(brandHex: 0x164B90), dark: Color(brandHex: 0xB8D3F8))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-warm-1` / `color.chart.diverging-warm-1-on-dark`.
    public static let chartDivergingWarm1 = Color(brandLight: Color(brandHex: 0xF37F54), dark: Color(brandHex: 0xB54E24))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-warm-2` / `color.chart.diverging-warm-2-on-dark`.
    public static let chartDivergingWarm2 = Color(brandLight: Color(brandHex: 0xD45C2C), dark: Color(brandHex: 0xE26330))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-warm-3` / `color.chart.diverging-warm-3-on-dark`.
    public static let chartDivergingWarm3 = Color(brandLight: Color(brandHex: 0x9F431F), dark: Color(brandHex: 0xF48F6A))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-cool-1` / `color.chart.diverging-cool-1-on-dark`.
    public static let chartDivergingCool1 = Color(brandLight: Color(brandHex: 0x70A6F2), dark: Color(brandHex: 0x256FCF))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-cool-2` / `color.chart.diverging-cool-2-on-dark`.
    public static let chartDivergingCool2 = Color(brandLight: Color(brandHex: 0x3484EE), dark: Color(brandHex: 0x488FEF))
    /// Rol claro/oscuro. Tokens `color.chart.diverging-cool-3` / `color.chart.diverging-cool-3-on-dark`.
    public static let chartDivergingCool3 = Color(brandLight: Color(brandHex: 0x1F61B6), dark: Color(brandHex: 0x80B0F3))
    /// Todos los roles por nombre, por ejemplo para pintar una paleta de muestra.
    public static let all: [(name: String, color: Color)] = [
        ("errorText", errorText),
        ("successText", successText),
        ("destructiveText", destructiveText),
        ("text", text),
        ("textPlaceholder", textPlaceholder),
        ("textMuted", textMuted),
        ("background", background),
        ("surfaceSecondary", surfaceSecondary),
        ("surfaceInverse", surfaceInverse),
        ("surfaceHighlight", surfaceHighlight),
        ("borderDefault", borderDefault),
        ("borderRecessive", borderRecessive),
        ("disabledBg", disabledBg),
        ("disabledText", disabledText),
        ("disabledBorder", disabledBorder),
        ("iconSecondary", iconSecondary),
        ("chartSeries1", chartSeries1),
        ("chartSeries2", chartSeries2),
        ("chartSeries3", chartSeries3),
        ("chartSeries4", chartSeries4),
        ("chartSeries5", chartSeries5),
        ("chartSeries6", chartSeries6),
        ("chartSeries7", chartSeries7),
        ("chartSeries8", chartSeries8),
        ("chartSequential100", chartSequential100),
        ("chartSequential200", chartSequential200),
        ("chartSequential300", chartSequential300),
        ("chartSequential400", chartSequential400),
        ("chartSequential500", chartSequential500),
        ("chartSequential600", chartSequential600),
        ("chartSequential700", chartSequential700),
        ("chartDivergingWarm1", chartDivergingWarm1),
        ("chartDivergingWarm2", chartDivergingWarm2),
        ("chartDivergingWarm3", chartDivergingWarm3),
        ("chartDivergingCool1", chartDivergingCool1),
        ("chartDivergingCool2", chartDivergingCool2),
        ("chartDivergingCool3", chartDivergingCool3),
    ]
}

/// Escala de espaciado, en puntos (`spacing.*`).
public enum BrandSpacing {
    /// Token `spacing.1` — 4px — dentro de un control: icono y texto, padding de un badge
    public static let s1: CGFloat = 4
    /// Token `spacing.2` — 8px — dentro de un control: padding de botones y campos, gap entre iconos
    public static let s2: CGFloat = 8
    /// Token `spacing.3` — 12px — entre elementos de un componente: filas de una lista, cabecera y cuerpo
    public static let s3: CGFloat = 12
    /// Token `spacing.4` — 16px — entre elementos de un componente; padding estándar de tarjetas y secciones
    public static let s4: CGFloat = 16
    /// Token `spacing.5` — 24px — entre componentes
    public static let s5: CGFloat = 24
    /// Token `spacing.6` — 32px — entre componentes; bloques de una página
    public static let s6: CGFloat = 32
    /// Token `spacing.7` — 48px — entre secciones
    public static let s7: CGFloat = 48
    /// Token `spacing.8` — 64px — entre secciones destacadas
    public static let s8: CGFloat = 64
}

/// Radios de esquina, en puntos (`border-radius.*`).
public enum BrandRadius {
    /// Token `border-radius.none` — Escala. Valor del rol default
    public static let none: CGFloat = 0
    /// Token `border-radius.sm` — Escala. El sistema no lo usa
    public static let sm: CGFloat = 4
    /// Token `border-radius.md` — Escala. El sistema no lo usa
    public static let md: CGFloat = 8
    /// Token `border-radius.lg` — Escala. El sistema no lo usa
    public static let lg: CGFloat = 12
    /// Token `border-radius.xl` — Escala. El sistema no lo usa
    public static let xl: CGFloat = 16
    /// Token `border-radius.full` — Escala. Valor del rol round
    public static let full: CGFloat = 9999
    /// Token `border-radius.default` — Rol: toda esquina del sistema es recta. Los componentes apuntan aquí, nunca a la escala
    public static let `default`: CGFloat = 0
    /// Token `border-radius.round` — Rol: píldoras y círculos — avatar, tag, badge, interruptor, botón píldora
    public static let round: CGFloat = 9999
}

/// Anchos de borde, en puntos (`border-width.*`).
public enum BrandBorderWidth {
    /// Token `border-width.sm` — Escala. Valor del rol default
    public static let sm: CGFloat = 1
    /// Token `border-width.md` — Escala. Valor del rol focus
    public static let md: CGFloat = 2
    /// Token `border-width.default` — Rol: todo borde del sistema. Los componentes apuntan aquí, nunca a la escala
    public static let `default`: CGFloat = 1
    /// Token `border-width.focus` — Rol: anillo de foco, ancho y separación. Solo para outline; nunca como borde
    public static let focus: CGFloat = 2
}

/// Tallas de control y objetivo táctil mínimo, en puntos (`size-component.*`, `size-target.*`).
public enum BrandSize {
    /// Token `size-component.sm` — 32px — talla mínima del sistema: controles compactos, avatares, iconos-botón, logos en barras
    public static let componentSm: CGFloat = 32
    /// Token `size-component.md` — 40px — talla por defecto de todo control de una línea: campos, selects, botones
    public static let componentMd: CGFloat = 40
    /// Token `size-component.lg` — 48px — controles destacados y objetivo táctil holgado
    public static let componentLg: CGFloat = 48
    /// Token `size-target.min` — 24px — objetivo de puntero mínimo (WCAG 2.5.8, nivel AA). No es una talla de maqueta: es el área sensible que un control pequeño (checkbox, radio) extiende de forma invisible más allá de su dibujo
    public static let targetMin: CGFloat = 24
}

/// Escala de opacidad (`opacity.*`).
public enum BrandOpacity {
    /// Token `opacity.full` — Extremo alto de una transición de opacidad: plenamente presente
    public static let full: Double = 1
    /// Token `opacity.muted` — Presente pero en segundo plano: un control secundario en reposo
    public static let muted: Double = 0.7
    /// Token `opacity.overlay` — Velo bajo un modal o una hoja: oscurece la página sin ocultarla
    public static let overlay: Double = 0.6
    /// Token `opacity.disabled` — Controles deshabilitados: el elemento sigue ahí, atenuado
    public static let disabled: Double = 0.4
}

/// Nombres de familia tipográfica (`font-family.*`), sin la pila de respaldo.
public enum BrandFontFamily {
    /// Token `font-family.sans` — Familia principal: interfaz y texto. Variable (peso 1-1000, tamaño óptico 6-144)
    public static let sans: String = "Google Sans Flex"
    /// Token `font-family.mono` — Código, valores técnicos y contenido preformateado
    public static let mono: String = "Google Sans Code"
    /// Token `font-family.serif` — Excepción de producto: no la usa ningún componente del sistema. Reservada para piezas editoriales o de marca que un producto decida tratar en serif
    public static let serif: String = "Libre Bodoni"
}

/// Escala de tamaños de fuente, en puntos (`font-size.*`).
public enum BrandFontSize {
    /// Token `font-size.0` — 12px — solo cifras dentro de marcas (contadores); nunca texto
    public static let s0: CGFloat = 12
    /// Token `font-size.1` — 14px — etiquetas de interfaz, texto pequeño
    public static let s1: CGFloat = 14
    /// Token `font-size.2` — 1rem (16px) — Body base
    public static let s2: CGFloat = 16
    /// Token `font-size.3` — 1.25rem (20px) — Small subtitles
    public static let s3: CGFloat = 20
    /// Token `font-size.4` — 1.5rem (24px) — Subtitles
    public static let s4: CGFloat = 24
    /// Token `font-size.5` — 1.75rem (28px) — Small titles
    public static let s5: CGFloat = 28
    /// Token `font-size.6` — 2rem (32px) — Titles
    public static let s6: CGFloat = 32
    /// Token `font-size.7` — 2.5rem (40px) — Large titles
    public static let s7: CGFloat = 40
    /// Token `font-size.8` — 3.5rem (56px) — Small display
    public static let s8: CGFloat = 56
    /// Token `font-size.9` — 4.5rem (72px) — Display
    public static let s9: CGFloat = 72
    /// Token `font-size.10` — 6rem (96px) — Large display
    public static let s10: CGFloat = 96
}

/// Pesos de la fuente variable (`font-weight.*`), como el valor numérico del eje `wght`.
public enum BrandFontWeight {
    /// Token `font-weight.thin` — Escala de la fuente variable. El sistema no lo usa
    public static let thin: Int = 100
    /// Token `font-weight.extralight` — Escala de la fuente variable. El sistema no lo usa
    public static let extralight: Int = 200
    /// Token `font-weight.light` — Cuerpo de texto (rol default)
    public static let light: Int = 300
    /// Token `font-weight.regular` — Escala de la fuente variable. El sistema no lo usa
    public static let regular: Int = 400
    /// Token `font-weight.medium` — Títulos y énfasis (rol emphasis)
    public static let medium: Int = 500
    /// Token `font-weight.semibold` — Escala de la fuente variable. El sistema no lo usa
    public static let semibold: Int = 600
    /// Token `font-weight.bold` — Escala de la fuente variable. El sistema no lo usa
    public static let bold: Int = 700
    /// Token `font-weight.extrabold` — Escala de la fuente variable. El sistema no lo usa
    public static let extrabold: Int = 800
    /// Token `font-weight.black` — Escala de la fuente variable. El sistema no lo usa
    public static let black: Int = 900
    /// Token `font-weight.default` — Rol: cuerpo de texto. Los componentes apuntan aquí, nunca a la escala
    public static let `default`: Int = 300
    /// Token `font-weight.emphasis` — Rol: títulos, énfasis local (strong, cifras destacadas), etiquetas. Dobla el trazo del cuerpo a 16px
    public static let emphasis: Int = 500
}

/// Interlineado como múltiplo del tamaño (`line-height.*`).
public enum BrandLineHeight {
    /// Token `line-height.none` — Single line elements, icons
    public static let none: CGFloat = 1
    /// Token `line-height.tight` — Display, large headings
    public static let tight: CGFloat = 1.1
    /// Token `line-height.snug` — Medium headings
    public static let snug: CGFloat = 1.3
    /// Token `line-height.normal` — Body text
    public static let normal: CGFloat = 1.5
    /// Token `line-height.relaxed` — 1,65 — lectura larga
    public static let relaxed: CGFloat = 1.65
}

/// Tracking como fracción del tamaño de fuente, en em (`letter-spacing.*`).
public enum BrandLetterSpacing {
    /// Token `letter-spacing.tight` — -0,02em — display y títulos grandes
    public static let tight: CGFloat = -0.02
    /// Token `letter-spacing.normal` — Body text
    public static let normal: CGFloat = 0
    /// Token `letter-spacing.wide` — Uppercase labels
    public static let wide: CGFloat = 0.05
}

/// Sombras (`shadow.*`). `blur` es el desenfoque de CSS: en SwiftUI, `radius` ≈ blur / 2.
public enum BrandShadows {
    /// Token `shadow.none` — Escala. Valor del rol default
    public static let none: BrandShadow = BrandShadow.none
    /// Token `shadow.sm` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.08 (sale como rgba(17,30,48,0.08))
    public static let sm: BrandShadow = BrandShadow(x: 0, y: 1, blur: 2, color: Color(brandHex: 0x111E30, opacity: 0.08))
    /// Token `shadow.md` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.10 (sale como rgba(17,30,48,0.10))
    public static let md: BrandShadow = BrandShadow(x: 0, y: 2, blur: 8, color: Color(brandHex: 0x111E30, opacity: 0.1))
    /// Token `shadow.lg` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.12 (sale como rgba(17,30,48,0.12))
    public static let lg: BrandShadow = BrandShadow(x: 0, y: 4, blur: 16, color: Color(brandHex: 0x111E30, opacity: 0.12))
    /// Token `shadow.xl` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.16 (sale como rgba(17,30,48,0.16))
    public static let xl: BrandShadow = BrandShadow(x: 0, y: 8, blur: 32, color: Color(brandHex: 0x111E30, opacity: 0.16))
    /// Token `shadow.default` — Rol: ningún elemento del sistema proyecta sombra. La elevación se expresa con borde y con el fondo del panel
    public static let `default`: BrandShadow = BrandShadow.none
}

/// Duraciones de movimiento, en segundos (`motion.duration.*`).
public enum BrandDuration {
    /// Token `motion.duration.instant` — Sin transición: cambios que deben ser inmediatos
    public static let instant: TimeInterval = 0
    /// Token `motion.duration.fast` — Respuesta a la interacción: hover, foco, pulsación
    public static let fast: TimeInterval = 0.15
    /// Token `motion.duration.base` — Cambios de estado: abrir un menú, mostrar un tooltip
    public static let base: TimeInterval = 0.25
    /// Token `motion.duration.slow` — Cambios de contexto: modales, hojas, paneles que entran
    public static let slow: TimeInterval = 0.4
}

/// Curvas de movimiento (`motion.easing.*`), como cubic-bezier de CSS.
public enum BrandEasing {
    /// Token `motion.easing.default` — Transiciones de propiedad: color, fondo, opacidad
    public static let `default`: BrandCubicBezier = BrandCubicBezier(0.25, 0.1, 0.25, 1)
    /// Token `motion.easing.in` — Escala. El sistema no lo usa
    public static let `in`: BrandCubicBezier = BrandCubicBezier(0.42, 0, 1, 1)
    /// Token `motion.easing.out` — Salidas: lo que desaparece frena al final
    public static let out: BrandCubicBezier = BrandCubicBezier(0, 0, 0.58, 1)
    /// Token `motion.easing.in-out` — Movimiento: paneles y hojas que se desplazan
    public static let inOut: BrandCubicBezier = BrandCubicBezier(0.42, 0, 0.58, 1)
    /// Token `motion.easing.linear` — Escala. El sistema no lo usa
    public static let linear: BrandCubicBezier = BrandCubicBezier.linear
}
