// Do not edit directly, this file was auto-generated by scripts/build-native-icons.mjs from src/stories/atoms/Icon/Icon.tsx. Run `pnpm build:native-icons`.

/// Los nombres del catálogo de iconos de React (`IconName`), con el `rawValue` igual al de React.
public enum BrandIconName: String, CaseIterable, Sendable {
    case arrow
    case arrowLeft = "arrow-left"
    case chevron
    case close
    case menu
    case dot
    case eye
    case eyeOff = "eye-off"
    case briefcase
    case chartInfographic = "chart-infographic"
    case dashboard
    case headset
    case layoutKanban = "layout-kanban"
    case reportMoney = "report-money"
    case shieldLock = "shield-lock"
    case minus
    case sparkles
    case usersGroup = "users-group"
    case folder
    case folderOpen = "folder-open"
    case trash
    case search
    case zoomIn = "zoom-in"
    case zoomOut = "zoom-out"
    case retry
    case lifebuoy
    case play
    case pause
    case stop
    case sun
    case moon
    case bell
    case bookOpen = "book-open"
    case chartBar = "chart-bar"
    case circleCheck = "circle-check"
    case check
    case chevronsUpDown = "chevrons-up-down"
    case creditCard = "credit-card"
    case copy
    case download
    case graduationCap = "graduation-cap"
    case key
    case logout
    case message
    case deviceDesktop = "device-desktop"
    case dots
    case grid
    case layoutSidebar = "layout-sidebar"
    case plus
    case receipt
    case fileText = "file-text"
    case settings
    case shieldCheck = "shield-check"
    case shield
    case star
    case upload
    case user
    case webhook
    case chevronRight = "chevron-right"
    case chevronDown = "chevron-down"
    case chevronUp = "chevron-up"
    case chevronLeft = "chevron-left"
    case info
    case alertTriangle = "alert-triangle"
    case alertError = "alert-error"
    case connection
    case package
    case archive
    case database
    case building
    case send
    case externalLink = "external-link"
    case gavel
    case inbox
    case library
    case calendar
    case target
    case languages
    case lock
    case layers
    case layers2 = "layers-2"
    case puzzle
    case images
    case paperclip
    case listCollapse = "list-collapse"
    case panelTop = "panel-top"
    case galleryHorizontal = "gallery-horizontal"
    case mousePointerClick = "mouse-pointer-click"
    case clock
    case circle
    case circleDot = "circle-dot"
    case circleDotDashed = "circle-dot-dashed"
    case squareCheck = "square-check"
    case toggleLeft = "toggle-left"
    case arrowUpDown = "arrow-up-down"
    case link
    case folderKanban = "folder-kanban"
    case textCursorInput = "text-cursor-input"
    case penLine = "pen-line"
    case moveHorizontal = "move-horizontal"
    case letterText = "letter-text"
    case personStanding = "person-standing"
    case gem
    case messageCircle = "message-circle"
    case messageSquareQuote = "message-square-quote"
    case headphones
    case deleteLeft = "delete-left"
}

extension BrandIconName {
    /// Los trazos del icono, en la retícula de 24 × 24 de la web.
    var shapes: [BrandIconShape] {
        switch self {
        case .arrow:
            [
                .path("M0 12 H24 M16 4 L24 12 L16 20"),
            ]
        case .arrowLeft:
            [
                .path("M24 12 H0 M8 4 L0 12 L8 20"),
            ]
        case .chevron:
            [
                .path("M7.5 3 L16.5 12 L7.5 21", round: true, roundJoin: true),
            ]
        case .close:
            [
                .path("M5.64 5.64 L18.36 18.36 M18.36 5.64 L5.64 18.36"),
            ]
        case .menu:
            [
                .line(x1: 3, y1: 6, x2: 21, y2: 6),
                .line(x1: 3, y1: 12, x2: 21, y2: 12),
                .line(x1: 3, y1: 18, x2: 21, y2: 18),
            ]
        case .dot:
            [
                .circle(cx: 12, cy: 12, r: 5, filled: true, stroked: false),
            ]
        case .eye:
            [
                .path("M3 12 C7.5 5.7 16.5 5.7 21 12 C16.5 18.3 7.5 18.3 3 12 Z"),
                .circle(cx: 12, cy: 12, r: 3.15),
            ]
        case .eyeOff:
            [
                .path("M3 12 C7.5 5.7 16.5 5.7 21 12 C16.5 18.3 7.5 18.3 3 12 Z"),
                .circle(cx: 12, cy: 12, r: 3.15),
                .path("M4 4 L20 20"),
            ]
        case .briefcase:
            [
                .path("M3 9a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2l0 -9", round: true, roundJoin: true),
                .path("M8 7v-2a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v2", round: true, roundJoin: true),
                .path("M12 12l0 .01", round: true, roundJoin: true),
                .path("M3 13a20 20 0 0 0 18 0", round: true, roundJoin: true),
            ]
        case .chartInfographic:
            [
                .path("M3 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0", round: true, roundJoin: true),
                .path("M7 3v4h4", round: true, roundJoin: true),
                .path("M9 17l0 4", round: true, roundJoin: true),
                .path("M17 14l0 7", round: true, roundJoin: true),
                .path("M13 13l0 8", round: true, roundJoin: true),
                .path("M21 12l0 9", round: true, roundJoin: true),
            ]
        case .dashboard:
            [
                .path("M4.5 3.5h4.5a1 1 0 0 1 1 1v6.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-6.5a1 1 0 0 1 1 -1", round: true, roundJoin: true),
                .path("M4.5 16h4.5a1 1 0 0 1 1 1v2.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-2.5a1 1 0 0 1 1 -1", round: true, roundJoin: true),
                .path("M15 12h4.5a1 1 0 0 1 1 1v6.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-6.5a1 1 0 0 1 1 -1", round: true, roundJoin: true),
                .path("M15 3.5h4.5a1 1 0 0 1 1 1v2.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-2.5a1 1 0 0 1 1 -1", round: true, roundJoin: true),
            ]
        case .headset:
            [
                .path("M4 14v-3a8 8 0 1 1 16 0v3", round: true, roundJoin: true),
                .path("M18 19c0 1.657 -2.686 3 -6 3", round: true, roundJoin: true),
                .path("M4 14a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round: true, roundJoin: true),
                .path("M15 14a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round: true, roundJoin: true),
            ]
        case .layoutKanban:
            [
                .path("M3.5 3.5l6.5 0", round: true, roundJoin: true),
                .path("M14 3.5l6.5 0", round: true, roundJoin: true),
                .path("M3.5 9.5a2 2 0 0 1 2 -2h2.5a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-2.5a2 2 0 0 1 -2 -2l0 -9", round: true, roundJoin: true),
                .path("M14 9.5a2 2 0 0 1 2 -2h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1 -2 2h-2.5a2 2 0 0 1 -2 -2l0 -2.5", round: true, roundJoin: true),
            ]
        case .reportMoney:
            [
                .path("M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2", round: true, roundJoin: true),
                .path("M9 5a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2", round: true, roundJoin: true),
                .path("M14 11h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5", round: true, roundJoin: true),
                .path("M12 17v1m0 -8v1", round: true, roundJoin: true),
            ]
        case .shieldLock:
            [
                .path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round: true, roundJoin: true),
                .path("M11 11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", round: true, roundJoin: true),
                .path("M12 12l0 2.5", round: true, roundJoin: true),
            ]
        case .minus:
            [
                .path("M4 12l16 0", round: true, roundJoin: true),
            ]
        case .sparkles:
            [
                .path("M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6", round: true, roundJoin: true),
            ]
        case .usersGroup:
            [
                .path("M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round: true, roundJoin: true),
                .path("M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1", round: true, roundJoin: true),
                .path("M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round: true, roundJoin: true),
                .path("M17 10h2a2 2 0 0 1 2 2v1", round: true, roundJoin: true),
                .path("M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round: true, roundJoin: true),
                .path("M3 13v-1a2 2 0 0 1 2 -2h2", round: true, roundJoin: true),
            ]
        case .folder:
            [
                .path("M21 18a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2V6a2 2 0 0 1 2 -2h4l2 3h8a2 2 0 0 1 2 2z", round: true, roundJoin: true),
            ]
        case .folderOpen:
            [
                .path("M5 20a2 2 0 0 1 -2 -2V6a2 2 0 0 1 2 -2h4l2 3h6a2 2 0 0 1 2 2v2M5 20l2.21 -8.26a1 1 0 0 1 .97 -.74H20a1 1 0 0 1 .98 1.2l-1.25 6.2a2 2 0 0 1 -1.96 1.6z", round: true, roundJoin: true),
            ]
        case .trash:
            [
                .path("M4 7l16 0", round: true, roundJoin: true),
                .path("M10 11l0 6", round: true, roundJoin: true),
                .path("M14 11l0 6", round: true, roundJoin: true),
                .path("M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12", round: true, roundJoin: true),
                .path("M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3", round: true, roundJoin: true),
            ]
        case .search:
            [
                .circle(cx: 11, cy: 11, r: 8),
                .path("M21 21 L16.65 16.65", round: true),
            ]
        case .zoomIn:
            [
                .circle(cx: 11, cy: 11, r: 8),
                .path("M21 21 L16.65 16.65", round: true),
                .path("M11 8 L11 14 M8 11 L14 11", round: true),
            ]
        case .zoomOut:
            [
                .circle(cx: 11, cy: 11, r: 8),
                .path("M21 21 L16.65 16.65", round: true),
                .path("M8 11 L14 11", round: true),
            ]
        case .retry:
            [
                .path("M3.07 10.875a9 9 0 1 1 .587 4.5m-.587 5.625v-5.625h5.625", round: true, roundJoin: true),
            ]
        case .lifebuoy:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .circle(cx: 12, cy: 12, r: 3),
                .path("M15 15 L18.5 18.5", round: true),
                .path("M9 15 L5.5 18.5", round: true),
                .path("M15 9 L18.5 5.5", round: true),
                .path("M9 9 L5.5 5.5", round: true),
            ]
        case .play:
            [
                .path("M6.5 3 L21 12 L6.5 21 Z", round: true, roundJoin: true),
            ]
        case .pause:
            [
                .path("M5.25 4a1 1 0 0 1 1 -1h2.5a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-2.5a1 1 0 0 1 -1 -1z", round: true, roundJoin: true),
                .path("M14.25 4a1 1 0 0 1 1 -1h2.5a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-2.5a1 1 0 0 1 -1 -1z", round: true, roundJoin: true),
            ]
        case .stop:
            [
                .path("M5 4h14a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1z", round: true, roundJoin: true),
            ]
        case .sun:
            [
                .path("M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"),
                .path("M12 3l0 1", round: true),
                .path("M12 20l0 1", round: true),
                .path("M3 12l1 0", round: true),
                .path("M20 12l1 0", round: true),
                .path("M5.6 5.6l.7 .7", round: true),
                .path("M17.7 17.7l.7 .7", round: true),
                .path("M5.6 18.4l.7 -.7", round: true),
                .path("M17.7 6.3l.7 -.7", round: true),
            ]
        case .moon:
            [
                .path("M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z", round: true, roundJoin: true),
            ]
        case .bell:
            [
                .path("M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6", round: true, roundJoin: true),
                .path("M9 17v1a3 3 0 0 0 6 0v-1", round: true, roundJoin: true),
            ]
        case .bookOpen:
            [
                .path("M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0", round: true, roundJoin: true),
                .path("M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0", round: true, roundJoin: true),
                .path("M3 6l0 13", round: true, roundJoin: true),
                .path("M12 6l0 13", round: true, roundJoin: true),
                .path("M21 6l0 13", round: true, roundJoin: true),
            ]
        case .chartBar:
            [
                .path("M3 3v16a2 2 0 0 0 2 2h16", round: true, roundJoin: true),
                .path("M8 17v-3", round: true, roundJoin: true),
                .path("M13 17V5", round: true, roundJoin: true),
                .path("M18 17V9", round: true, roundJoin: true),
            ]
        case .circleCheck:
            [
                .path("M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
                .path("M9 12l2 2l4 -4", round: true, roundJoin: true),
            ]
        case .check:
            [
                .path("M4 12l5.33 5.33l10.67 -10.67", round: true, roundJoin: true),
            ]
        case .chevronsUpDown:
            [
                .path("M5 10l7 -7l7 7", round: true, roundJoin: true),
                .path("M19 14l-7 7l-7 -7", round: true, roundJoin: true),
            ]
        case .creditCard:
            [
                .path("M3 5m0 3a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3z", round: true, roundJoin: true),
                .path("M3 10l18 0", round: true, roundJoin: true),
                .path("M7 15l.01 0", round: true, roundJoin: true),
                .path("M11 15l2 0", round: true, roundJoin: true),
            ]
        case .copy:
            [
                .path("M8 8m0 2a2 2 0 0 1 2 -2h9a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-9a2 2 0 0 1 -2 -2z", round: true, roundJoin: true),
                .path("M16 8v-2a2 2 0 0 0 -2 -2h-9a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h2", round: true, roundJoin: true),
            ]
        case .download:
            [
                .path("M3 17v2a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-2", round: true, roundJoin: true),
                .path("M6 10l6 6l6 -6", round: true, roundJoin: true),
                .path("M12 3l0 13", round: true, roundJoin: true),
            ]
        case .graduationCap:
            [
                .path("M21 9.3l-9 -3.6l-9 3.6l9 3.6l9 -3.6v5.4", round: true, roundJoin: true),
                .path("M6.6 10.74v4.86a5.4 2.7 0 0 0 10.8 0v-4.86", round: true, roundJoin: true),
            ]
        case .key:
            [
                .path("M16.555 3.843l3.602 3.602a2.877 2.877 0 0 1 0 4.069l-2.643 2.643a2.877 2.877 0 0 1 -4.069 0l-.301 -.301l-6.558 6.558a2 2 0 0 1 -1.239 .578l-.175 .008h-1.172a1 1 0 0 1 -.993 -.883l-.007 -.117v-1.172a2 2 0 0 1 .467 -1.284l.119 -.13l.414 -.414h2v-2h2v-2l2.144 -2.144l-.301 -.301a2.877 2.877 0 0 1 0 -4.069l2.643 -2.643a2.877 2.877 0 0 1 4.069 0z", round: true, roundJoin: true),
                .path("M15 9m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"),
            ]
        case .logout:
            [
                .path("M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2", round: true, roundJoin: true),
                .path("M7 12h14l-3 -3", round: true, roundJoin: true),
                .path("M18 15l3 -3", round: true, roundJoin: true),
            ]
        case .message:
            [
                .path("M18 4a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3z", round: true, roundJoin: true),
                .path("M8 9l8 0", round: true, roundJoin: true),
                .path("M8 13l6 0", round: true, roundJoin: true),
            ]
        case .deviceDesktop:
            [
                .path("M3 5m0 1a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1z", round: true, roundJoin: true),
                .path("M7 20l10 0", round: true, roundJoin: true),
                .path("M9 16l0 4", round: true, roundJoin: true),
                .path("M15 16l0 4", round: true, roundJoin: true),
            ]
        case .dots:
            [
                .circle(cx: 5, cy: 12, r: 1.5, filled: true, stroked: false),
                .circle(cx: 12, cy: 12, r: 1.5, filled: true, stroked: false),
                .circle(cx: 19, cy: 12, r: 1.5, filled: true, stroked: false),
            ]
        case .grid:
            [
                .circle(cx: 5, cy: 5, r: 1.5, filled: true, stroked: false),
                .circle(cx: 12, cy: 5, r: 1.5, filled: true, stroked: false),
                .circle(cx: 19, cy: 5, r: 1.5, filled: true, stroked: false),
                .circle(cx: 5, cy: 12, r: 1.5, filled: true, stroked: false),
                .circle(cx: 12, cy: 12, r: 1.5, filled: true, stroked: false),
                .circle(cx: 19, cy: 12, r: 1.5, filled: true, stroked: false),
                .circle(cx: 5, cy: 19, r: 1.5, filled: true, stroked: false),
                .circle(cx: 12, cy: 19, r: 1.5, filled: true, stroked: false),
                .circle(cx: 19, cy: 19, r: 1.5, filled: true, stroked: false),
            ]
        case .layoutSidebar:
            [
                .path("M3.5 3.5m0 2a2 2 0 0 1 2 -2h13a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-13a2 2 0 0 1 -2 -2z", round: true, roundJoin: true),
                .path("M9 3.5l0 17", round: true, roundJoin: true),
            ]
        case .plus:
            [
                .path("M12 4l0 16", round: true, roundJoin: true),
                .path("M4 12l16 0", round: true, roundJoin: true),
            ]
        case .receipt:
            [
                .path("M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2", round: true, roundJoin: true),
                .path("M10 8l4 0", round: true, roundJoin: true),
                .path("M10 12l4 0", round: true, roundJoin: true),
            ]
        case .fileText:
            [
                .path("M14 3v4a1 1 0 0 0 1 1h4", round: true, roundJoin: true),
                .path("M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z", round: true, roundJoin: true),
                .path("M9 9l1 0", round: true, roundJoin: true),
                .path("M9 13l6 0", round: true, roundJoin: true),
                .path("M9 17l6 0", round: true, roundJoin: true),
            ]
        case .settings:
            [
                .path("M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z", round: true, roundJoin: true),
                .path("M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"),
            ]
        case .shieldCheck:
            [
                .path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round: true, roundJoin: true),
                .path("M9 12l2 2l4 -4", round: true, roundJoin: true),
            ]
        case .shield:
            [
                .path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round: true, roundJoin: true),
            ]
        case .star:
            [
                .path("M12 2.8 L14.12 9.09 L20.75 9.16 L15.42 13.11 L17.41 19.44 L12 15.6 L6.59 19.44 L8.58 13.11 L3.25 9.16 L9.88 9.09 Z", round: true, roundJoin: true),
            ]
        case .upload:
            [
                .path("M12 17V3", round: true, roundJoin: true),
                .path("M6 9l6 -6l6 6", round: true, roundJoin: true),
                .path("M3 21h18", round: true, roundJoin: true),
            ]
        case .user:
            [
                .path("M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"),
                .path("M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2", round: true, roundJoin: true),
            ]
        case .webhook:
            [
                .circle(cx: 17, cy: 17, r: 3),
                .circle(cx: 6.5, cy: 10, r: 3.5),
                .circle(cx: 14, cy: 6, r: 3),
                .path("M9.5 8.7 L11.8 4.3", round: true),
                .path("M8.5 12.8 L14.7 16.4", round: true),
                .path("M15.7 8.2 L17 14", round: true),
            ]
        case .chevronRight:
            [
                .path("M7.5 3 L16.5 12 L7.5 21", round: true, roundJoin: true),
            ]
        case .chevronDown:
            [
                .path("M21 7.5 L12 16.5 L3 7.5", round: true, roundJoin: true),
            ]
        case .chevronUp:
            [
                .path("M3 16.5 L12 7.5 L21 16.5", round: true, roundJoin: true),
            ]
        case .chevronLeft:
            [
                .path("M16.5 3 L7.5 12 L16.5 21", round: true, roundJoin: true),
            ]
        case .info:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .path("M12 7.5l0 .01", round: true),
                .path("M12 11l0 5", round: true),
            ]
        case .alertTriangle:
            [
                .path("M12 3 L21 20 H3 Z", round: true, roundJoin: true),
                .path("M12 9l0 5", round: true),
                .path("M12 17l0 .01", round: true),
            ]
        case .alertError:
            [
                .path("M8 3h8l5 5v8l-5 5h-8l-5 -5v-8z", round: true, roundJoin: true),
                .path("M9 9l6 6M15 9l-6 6", round: true),
            ]
        case .connection:
            [
                .path("M9 3l0 3M15 3l0 3", round: true),
                .path("M6.5 6h11v2.5a5.5 5.5 0 0 1 -11 0z", round: true, roundJoin: true),
                .path("M12 14l0 2l-2 2.5h4l-2 2.5", round: true, roundJoin: true),
            ]
        case .package:
            [
                .path("M12 3l8 4.5v9l-8 4.5l-8 -4.5v-9z", round: true, roundJoin: true),
                .path("M12 12l8 -4.5M12 12l0 9M12 12l-8 -4.5", round: true, roundJoin: true),
            ]
        case .archive:
            [
                .path("M4 4a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1z", round: true, roundJoin: true),
                .path("M5 9l0 9a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2l0 -9", round: true, roundJoin: true),
                .path("M10 13l4 0", round: true),
            ]
        case .database:
            [
                .path("M3 6a9 3 0 1 0 18 0a9 3 0 1 0 -18 0", round: true, roundJoin: true),
                .path("M3 6l0 6a9 3 0 0 0 18 0l0 -6", round: true, roundJoin: true),
                .path("M3 12l0 6a9 3 0 0 0 18 0l0 -6", round: true, roundJoin: true),
            ]
        case .building:
            [
                .path("M5 21l0 -16a2 2 0 0 1 2 -2l10 0a2 2 0 0 1 2 2l0 16", round: true, roundJoin: true),
                .path("M3 21l18 0", round: true),
                .path("M9 8l.01 0M15 8l.01 0M9 12l.01 0M15 12l.01 0M9 16l.01 0M15 16l.01 0", round: true),
            ]
        case .send:
            [
                .path("M3 21l18 -9l-18 -9l0 7.31l11.25 1.69l-11.25 1.69z", round: true, roundJoin: true),
            ]
        case .externalLink:
            [
                .path("M19 13l0 6a2 2 0 0 1 -2 2l-10 0a2 2 0 0 1 -2 -2l0 -10a2 2 0 0 1 2 -2l6 0", round: true, roundJoin: true),
                .path("M15 3l6 0l0 6", round: true, roundJoin: true),
                .path("M9 15l12 -12", round: true),
            ]
        case .gavel:
            [
                .path("M19 8l-3 -3l-8 8l3 3z", round: true, roundJoin: true),
                .path("M11 13l-5 5", round: true),
                .path("M3 21l8 0", round: true),
            ]
        case .inbox:
            [
                .path("M3 12L6.45 5.11A2 2 0 0 1 8.24 4H15.76A2 2 0 0 1 17.55 5.11L21 12V18A2 2 0 0 1 19 20H5A2 2 0 0 1 3 18Z", round: true, roundJoin: true),
                .path("M21 12h-5l-2 3h-4l-2 -3H3", round: true, roundJoin: true),
            ]
        case .library:
            [
                .path("M4 21l0 -15a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 15", round: true, roundJoin: true),
                .path("M10 21l0 -17a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 17", round: true, roundJoin: true),
                .path("M16 21l0 -13a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 13", round: true, roundJoin: true),
                .path("M3 21l18 0", round: true),
            ]
        case .calendar:
            [
                .path("M5 6h14a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
                .path("M3 10 H21", round: true),
                .path("M8 4 V8", round: true),
                .path("M16 4 V8", round: true),
            ]
        case .target:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .circle(cx: 12, cy: 12, r: 5),
                .circle(cx: 12, cy: 12, r: 1),
            ]
        case .languages:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .path("M3 12l18 0", round: true),
                .path("M12 3a14 14 0 0 1 0 18a14 14 0 0 1 0 -18", round: true, roundJoin: true),
            ]
        case .lock:
            [
                .path("M7 10.5h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
                .path("M8 10.5v-3a4 4 0 0 1 8 0v3", round: true, roundJoin: true),
            ]
        case .layers:
            [
                .path("M12 3l9 4.5l-9 4.5l-9 -4.5z", round: true, roundJoin: true),
                .path("M3 12l9 4.5l9 -4.5", round: true, roundJoin: true),
                .path("M3 16.5l9 4.5l9 -4.5", round: true, roundJoin: true),
            ]
        case .layers2:
            [
                .path("M12 5.25l9 4.5l-9 4.5l-9 -4.5z", round: true, roundJoin: true),
                .path("M3 14.25l9 4.5l9 -4.5", round: true, roundJoin: true),
            ]
        case .puzzle:
            [
                .path("M5.5 7.5h2.5a2.5 2.5 0 1 1 4 0h2.5a2 2 0 0 1 2 2v2.5a2.5 2.5 0 1 1 0 4v2.5a2 2 0 0 1 -2 2h-9a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
            ]
        case .images:
            [
                .path("M7 7v-2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-2", round: true, roundJoin: true),
                .path("M5 7h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
                .path("M3 18l4 -4l7 7", round: true, roundJoin: true),
                .circle(cx: 12.5, cy: 11.5, r: 1.5),
            ]
        case .paperclip:
            [
                .path("M16.74 12.91L11.44 18.22A3.5 3.5 0 0 1 6.49 13.27L14.27 5.49A2.5 2.5 0 0 1 17.8 9.03L10.03 16.8A1.75 1.75 0 0 1 7.55 14.33L12.85 9.03", round: true, roundJoin: true),
            ]
        case .listCollapse:
            [
                .path("M3 3l3 3l-3 3", round: true, roundJoin: true),
                .path("M3 15l3 3l-3 3", round: true, roundJoin: true),
                .path("M10 6h11", round: true, roundJoin: true),
                .path("M10 12h11", round: true, roundJoin: true),
                .path("M10 18h11", round: true, roundJoin: true),
            ]
        case .panelTop:
            [
                .path("M5.5 3.5h13a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-13a2 2 0 0 1 -2 -2v-13a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
                .path("M3.5 9l17 0", round: true, roundJoin: true),
            ]
        case .galleryHorizontal:
            [
                .path("M3.5 3.5l0 17", round: true, roundJoin: true),
                .path("M20.5 3.5l0 17", round: true, roundJoin: true),
                .path("M9 3.5h6a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-6a2 2 0 0 1 -2 -2v-13a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
            ]
        case .mousePointerClick:
            [
                .path("M9 9l11 4.5l-4.5 2l-2 4.5z", round: true, roundJoin: true),
                .path("M9 3l0 2.5", round: true, roundJoin: true),
                .path("M3 9l2.5 0", round: true, roundJoin: true),
                .path("M13.5 4.5l-1.75 1.75", round: true, roundJoin: true),
                .path("M4.5 13.5l1.75 -1.75", round: true, roundJoin: true),
            ]
        case .clock:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .path("M12 7l0 5l3 3", round: true, roundJoin: true),
            ]
        case .circle:
            [
                .circle(cx: 12, cy: 12, r: 9),
            ]
        case .circleDot:
            [
                .circle(cx: 12, cy: 12, r: 9),
                .circle(cx: 12, cy: 12, r: 1),
            ]
        case .circleDotDashed:
            [
                .path("M13.17 3.08A9 9 0 0 1 17.48 4.86M19.14 6.52A9 9 0 0 1 20.92 10.83M20.92 13.17A9 9 0 0 1 19.14 17.48M17.48 19.14A9 9 0 0 1 13.17 20.92M10.83 20.92A9 9 0 0 1 6.52 19.14M4.86 17.48A9 9 0 0 1 3.08 13.17M3.08 10.83A9 9 0 0 1 4.86 6.52M6.52 4.86A9 9 0 0 1 10.83 3.08", round: true, roundJoin: true),
                .circle(cx: 12, cy: 12, r: 1),
            ]
        case .squareCheck:
            [
                .path("M5.5 3.5h13a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-13a2 2 0 0 1 -2 -2v-13a2 2 0 0 1 2 -2z", round: true, roundJoin: true),
                .path("M9 12l2 2l4 -4", round: true, roundJoin: true),
            ]
        case .toggleLeft:
            [
                .path("M8.5 6.5h7a5.5 5.5 0 0 1 0 11h-7a5.5 5.5 0 0 1 0 -11z", round: true, roundJoin: true),
                .circle(cx: 8.5, cy: 12, r: 2.5),
            ]
        case .arrowUpDown:
            [
                .path("M7 21l0 -18", round: true, roundJoin: true),
                .path("M3 7l4 -4l4 4", round: true, roundJoin: true),
                .path("M17 3l0 18", round: true, roundJoin: true),
                .path("M13 17l4 4l4 -4", round: true, roundJoin: true),
            ]
        case .link:
            [
                .path("M8.11 10.94L5.64 13.41A3.5 3.5 0 0 0 10.59 18.36L13.06 15.89", round: true, roundJoin: true),
                .path("M10.94 8.11L13.41 5.64A3.5 3.5 0 0 1 18.36 10.59L15.89 13.06", round: true, roundJoin: true),
                .path("M9.88 14.12L14.12 9.88", round: true, roundJoin: true),
            ]
        case .folderKanban:
            [
                .path("M21 18a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2V6a2 2 0 0 1 2 -2h4l2 3h8a2 2 0 0 1 2 2z", round: true, roundJoin: true),
                .path("M8 11l0 4", round: true, roundJoin: true),
                .path("M12 11l0 2", round: true, roundJoin: true),
                .path("M16 11l0 6", round: true, roundJoin: true),
            ]
        case .textCursorInput:
            [
                .path("M6 8h-1a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h1", round: true, roundJoin: true),
                .path("M12 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-7", round: true, roundJoin: true),
                .path("M9 4l0 16", round: true, roundJoin: true),
                .path("M7 4l4 0", round: true, roundJoin: true),
                .path("M7 20l4 0", round: true, roundJoin: true),
            ]
        case .penLine:
            [
                .path("M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4", round: true, roundJoin: true),
                .path("M13.5 6.5l4 4", round: true, roundJoin: true),
                .path("M12 20l8 0", round: true, roundJoin: true),
            ]
        case .moveHorizontal:
            [
                .path("M3 12l18 0", round: true, roundJoin: true),
                .path("M7 8l-4 4l4 4", round: true, roundJoin: true),
                .path("M17 8l4 4l-4 4", round: true, roundJoin: true),
            ]
        case .letterText:
            [
                .path("M3 12.5l4 -8l4 8", round: true, roundJoin: true),
                .path("M4.5 9.5l5 0", round: true, roundJoin: true),
                .path("M15 5.5l6 0", round: true, roundJoin: true),
                .path("M15 12.5l6 0", round: true, roundJoin: true),
                .path("M3 19.5l18 0", round: true, roundJoin: true),
            ]
        case .personStanding:
            [
                .circle(cx: 12, cy: 4.5, r: 1.5),
                .path("M6 8.5l6 2l6 -2", round: true, roundJoin: true),
                .path("M12 10.5l0 4", round: true, roundJoin: true),
                .path("M9 21l3 -6.5l3 6.5", round: true, roundJoin: true),
            ]
        case .gem:
            [
                .path("M7 4h10l4 5l-9 11l-9 -11z", round: true, roundJoin: true),
                .path("M3 9l18 0", round: true, roundJoin: true),
                .path("M10 4l-2 5l4 11l4 -11l-2 -5", round: true, roundJoin: true),
            ]
        case .messageCircle:
            [
                .path("M7.5 19.79A9 9 0 1 0 4.21 16.5L3 21z", round: true, roundJoin: true),
            ]
        case .messageSquareQuote:
            [
                .path("M18 4a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3z", round: true, roundJoin: true),
                .path("M9 8.5h2v3a2 2 0 0 1 -2 2", round: true, roundJoin: true),
                .path("M13 8.5h2v3a2 2 0 0 1 -2 2", round: true, roundJoin: true),
            ]
        case .headphones:
            [
                .path("M4 15v-3a8 8 0 1 1 16 0v3", round: true, roundJoin: true),
                .path("M4 15a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round: true, roundJoin: true),
                .path("M15 15a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round: true, roundJoin: true),
            ]
        case .deleteLeft:
            [
                .path("M9 5h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10l-6 -7z", round: true, roundJoin: true),
                .path("M12.5 9.5l5 5M17.5 9.5l-5 5", round: true, roundJoin: true),
            ]
        }
    }
}
