// Do not edit directly, this file was auto-generated by scripts/build-native-icons.mjs from src/stories/atoms/Icon/Icon.tsx. Run `pnpm build:native-icons`.

package com.studiolxd.brand.icon

/** Los nombres del catálogo de iconos de React (`IconName`); `value` es el nombre de React. */
enum class BrandIconName(val value: String) {
    Arrow("arrow"),
    ArrowLeft("arrow-left"),
    Chevron("chevron"),
    Close("close"),
    Menu("menu"),
    Dot("dot"),
    Eye("eye"),
    EyeOff("eye-off"),
    Briefcase("briefcase"),
    ChartInfographic("chart-infographic"),
    Dashboard("dashboard"),
    Headset("headset"),
    LayoutKanban("layout-kanban"),
    ReportMoney("report-money"),
    ShieldLock("shield-lock"),
    Minus("minus"),
    Sparkles("sparkles"),
    UsersGroup("users-group"),
    Folder("folder"),
    FolderOpen("folder-open"),
    Trash("trash"),
    Search("search"),
    ZoomIn("zoom-in"),
    ZoomOut("zoom-out"),
    Retry("retry"),
    Lifebuoy("lifebuoy"),
    Play("play"),
    Pause("pause"),
    Stop("stop"),
    Sun("sun"),
    Moon("moon"),
    Bell("bell"),
    BookOpen("book-open"),
    ChartBar("chart-bar"),
    CircleCheck("circle-check"),
    Check("check"),
    ChevronsUpDown("chevrons-up-down"),
    CreditCard("credit-card"),
    Copy("copy"),
    Download("download"),
    GraduationCap("graduation-cap"),
    Key("key"),
    Logout("logout"),
    Message("message"),
    DeviceDesktop("device-desktop"),
    Dots("dots"),
    Grid("grid"),
    LayoutSidebar("layout-sidebar"),
    Plus("plus"),
    Receipt("receipt"),
    FileText("file-text"),
    Settings("settings"),
    ShieldCheck("shield-check"),
    Shield("shield"),
    Star("star"),
    Upload("upload"),
    User("user"),
    Webhook("webhook"),
    ChevronRight("chevron-right"),
    ChevronDown("chevron-down"),
    ChevronUp("chevron-up"),
    Info("info"),
    AlertTriangle("alert-triangle"),
    AlertError("alert-error"),
    Connection("connection"),
    Package("package"),
    Archive("archive"),
    Database("database"),
    Building("building"),
    Send("send"),
    ExternalLink("external-link"),
    Gavel("gavel"),
    Inbox("inbox"),
    Library("library"),
    Calendar("calendar"),
    Target("target"),
    Languages("languages");
}

/** Los trazos del icono, en la retícula de 24 × 24 de la web. */
internal val BrandIconName.shapes: List<BrandIconShape>
    get() = when (this) {
        BrandIconName.Arrow -> listOf(
            BrandIconShape.Path("M0 12 H24 M16 4 L24 12 L16 20"),
        )
        BrandIconName.ArrowLeft -> listOf(
            BrandIconShape.Path("M24 12 H0 M8 4 L0 12 L8 20"),
        )
        BrandIconName.Chevron -> listOf(
            BrandIconShape.Path("M7.5 3 L16.5 12 L7.5 21", round = true, roundJoin = true),
        )
        BrandIconName.Close -> listOf(
            BrandIconShape.Path("M5.64 5.64 L18.36 18.36 M18.36 5.64 L5.64 18.36"),
        )
        BrandIconName.Menu -> listOf(
            BrandIconShape.Line(3f, 6f, 21f, 6f),
            BrandIconShape.Line(3f, 12f, 21f, 12f),
            BrandIconShape.Line(3f, 18f, 21f, 18f),
        )
        BrandIconName.Dot -> listOf(
            BrandIconShape.Circle(12f, 12f, 5f, filled = true, stroked = false),
        )
        BrandIconName.Eye -> listOf(
            BrandIconShape.Path("M3 12 C7.5 5.7 16.5 5.7 21 12 C16.5 18.3 7.5 18.3 3 12 Z"),
            BrandIconShape.Circle(12f, 12f, 3.15f),
        )
        BrandIconName.EyeOff -> listOf(
            BrandIconShape.Path("M3 12 C7.5 5.7 16.5 5.7 21 12 C16.5 18.3 7.5 18.3 3 12 Z"),
            BrandIconShape.Circle(12f, 12f, 3.15f),
            BrandIconShape.Path("M4 4 L20 20"),
        )
        BrandIconName.Briefcase -> listOf(
            BrandIconShape.Path("M3 9a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2l0 -9", round = true, roundJoin = true),
            BrandIconShape.Path("M8 7v-2a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v2", round = true, roundJoin = true),
            BrandIconShape.Path("M12 12l0 .01", round = true, roundJoin = true),
            BrandIconShape.Path("M3 13a20 20 0 0 0 18 0", round = true, roundJoin = true),
        )
        BrandIconName.ChartInfographic -> listOf(
            BrandIconShape.Path("M3 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0", round = true, roundJoin = true),
            BrandIconShape.Path("M7 3v4h4", round = true, roundJoin = true),
            BrandIconShape.Path("M9 17l0 4", round = true, roundJoin = true),
            BrandIconShape.Path("M17 14l0 7", round = true, roundJoin = true),
            BrandIconShape.Path("M13 13l0 8", round = true, roundJoin = true),
            BrandIconShape.Path("M21 12l0 9", round = true, roundJoin = true),
        )
        BrandIconName.Dashboard -> listOf(
            BrandIconShape.Path("M4.5 3.5h4.5a1 1 0 0 1 1 1v6.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-6.5a1 1 0 0 1 1 -1", round = true, roundJoin = true),
            BrandIconShape.Path("M4.5 16h4.5a1 1 0 0 1 1 1v2.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-2.5a1 1 0 0 1 1 -1", round = true, roundJoin = true),
            BrandIconShape.Path("M15 12h4.5a1 1 0 0 1 1 1v6.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-6.5a1 1 0 0 1 1 -1", round = true, roundJoin = true),
            BrandIconShape.Path("M15 3.5h4.5a1 1 0 0 1 1 1v2.5a1 1 0 0 1 -1 1h-4.5a1 1 0 0 1 -1 -1v-2.5a1 1 0 0 1 1 -1", round = true, roundJoin = true),
        )
        BrandIconName.Headset -> listOf(
            BrandIconShape.Path("M4 14v-3a8 8 0 1 1 16 0v3", round = true, roundJoin = true),
            BrandIconShape.Path("M18 19c0 1.657 -2.686 3 -6 3", round = true, roundJoin = true),
            BrandIconShape.Path("M4 14a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round = true, roundJoin = true),
            BrandIconShape.Path("M15 14a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-1a2 2 0 0 1 -2 -2v-3", round = true, roundJoin = true),
        )
        BrandIconName.LayoutKanban -> listOf(
            BrandIconShape.Path("M3.5 3.5l6.5 0", round = true, roundJoin = true),
            BrandIconShape.Path("M14 3.5l6.5 0", round = true, roundJoin = true),
            BrandIconShape.Path("M3.5 9.5a2 2 0 0 1 2 -2h2.5a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-2.5a2 2 0 0 1 -2 -2l0 -9", round = true, roundJoin = true),
            BrandIconShape.Path("M14 9.5a2 2 0 0 1 2 -2h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1 -2 2h-2.5a2 2 0 0 1 -2 -2l0 -2.5", round = true, roundJoin = true),
        )
        BrandIconName.ReportMoney -> listOf(
            BrandIconShape.Path("M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2", round = true, roundJoin = true),
            BrandIconShape.Path("M9 5a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2", round = true, roundJoin = true),
            BrandIconShape.Path("M14 11h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5", round = true, roundJoin = true),
            BrandIconShape.Path("M12 17v1m0 -8v1", round = true, roundJoin = true),
        )
        BrandIconName.ShieldLock -> listOf(
            BrandIconShape.Path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round = true, roundJoin = true),
            BrandIconShape.Path("M11 11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", round = true, roundJoin = true),
            BrandIconShape.Path("M12 12l0 2.5", round = true, roundJoin = true),
        )
        BrandIconName.Minus -> listOf(
            BrandIconShape.Path("M4 12l16 0", round = true, roundJoin = true),
        )
        BrandIconName.Sparkles -> listOf(
            BrandIconShape.Path("M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6", round = true, roundJoin = true),
        )
        BrandIconName.UsersGroup -> listOf(
            BrandIconShape.Path("M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round = true, roundJoin = true),
            BrandIconShape.Path("M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1", round = true, roundJoin = true),
            BrandIconShape.Path("M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round = true, roundJoin = true),
            BrandIconShape.Path("M17 10h2a2 2 0 0 1 2 2v1", round = true, roundJoin = true),
            BrandIconShape.Path("M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", round = true, roundJoin = true),
            BrandIconShape.Path("M3 13v-1a2 2 0 0 1 2 -2h2", round = true, roundJoin = true),
        )
        BrandIconName.Folder -> listOf(
            BrandIconShape.Path("M21 18a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2V6a2 2 0 0 1 2 -2h4l2 3h8a2 2 0 0 1 2 2z", round = true, roundJoin = true),
        )
        BrandIconName.FolderOpen -> listOf(
            BrandIconShape.Path("M5 20a2 2 0 0 1 -2 -2V6a2 2 0 0 1 2 -2h4l2 3h6a2 2 0 0 1 2 2v2M5 20l2.21 -8.26a1 1 0 0 1 .97 -.74H20a1 1 0 0 1 .98 1.2l-1.25 6.2a2 2 0 0 1 -1.96 1.6z", round = true, roundJoin = true),
        )
        BrandIconName.Trash -> listOf(
            BrandIconShape.Path("M4 7l16 0", round = true, roundJoin = true),
            BrandIconShape.Path("M10 11l0 6", round = true, roundJoin = true),
            BrandIconShape.Path("M14 11l0 6", round = true, roundJoin = true),
            BrandIconShape.Path("M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12", round = true, roundJoin = true),
            BrandIconShape.Path("M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3", round = true, roundJoin = true),
        )
        BrandIconName.Search -> listOf(
            BrandIconShape.Circle(11f, 11f, 8f),
            BrandIconShape.Path("M21 21 L16.65 16.65", round = true),
        )
        BrandIconName.ZoomIn -> listOf(
            BrandIconShape.Circle(11f, 11f, 8f),
            BrandIconShape.Path("M21 21 L16.65 16.65", round = true),
            BrandIconShape.Path("M11 8 L11 14 M8 11 L14 11", round = true),
        )
        BrandIconName.ZoomOut -> listOf(
            BrandIconShape.Circle(11f, 11f, 8f),
            BrandIconShape.Path("M21 21 L16.65 16.65", round = true),
            BrandIconShape.Path("M8 11 L14 11", round = true),
        )
        BrandIconName.Retry -> listOf(
            BrandIconShape.Path("M3.07 10.875a9 9 0 1 1 .587 4.5m-.587 5.625v-5.625h5.625", round = true, roundJoin = true),
        )
        BrandIconName.Lifebuoy -> listOf(
            BrandIconShape.Circle(12f, 12f, 9f),
            BrandIconShape.Circle(12f, 12f, 3f),
            BrandIconShape.Path("M15 15 L18.5 18.5", round = true),
            BrandIconShape.Path("M9 15 L5.5 18.5", round = true),
            BrandIconShape.Path("M15 9 L18.5 5.5", round = true),
            BrandIconShape.Path("M9 9 L5.5 5.5", round = true),
        )
        BrandIconName.Play -> listOf(
            BrandIconShape.Path("M6.5 3 L21 12 L6.5 21 Z", round = true, roundJoin = true),
        )
        BrandIconName.Pause -> listOf(
            BrandIconShape.Path("M5.25 4a1 1 0 0 1 1 -1h2.5a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-2.5a1 1 0 0 1 -1 -1z", round = true, roundJoin = true),
            BrandIconShape.Path("M14.25 4a1 1 0 0 1 1 -1h2.5a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-2.5a1 1 0 0 1 -1 -1z", round = true, roundJoin = true),
        )
        BrandIconName.Stop -> listOf(
            BrandIconShape.Path("M5 4h14a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1z", round = true, roundJoin = true),
        )
        BrandIconName.Sun -> listOf(
            BrandIconShape.Path("M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"),
            BrandIconShape.Path("M12 3l0 1", round = true),
            BrandIconShape.Path("M12 20l0 1", round = true),
            BrandIconShape.Path("M3 12l1 0", round = true),
            BrandIconShape.Path("M20 12l1 0", round = true),
            BrandIconShape.Path("M5.6 5.6l.7 .7", round = true),
            BrandIconShape.Path("M17.7 17.7l.7 .7", round = true),
            BrandIconShape.Path("M5.6 18.4l.7 -.7", round = true),
            BrandIconShape.Path("M17.7 6.3l.7 -.7", round = true),
        )
        BrandIconName.Moon -> listOf(
            BrandIconShape.Path("M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z", round = true, roundJoin = true),
        )
        BrandIconName.Bell -> listOf(
            BrandIconShape.Path("M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6", round = true, roundJoin = true),
            BrandIconShape.Path("M9 17v1a3 3 0 0 0 6 0v-1", round = true, roundJoin = true),
        )
        BrandIconName.BookOpen -> listOf(
            BrandIconShape.Path("M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0", round = true, roundJoin = true),
            BrandIconShape.Path("M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0", round = true, roundJoin = true),
            BrandIconShape.Path("M3 6l0 13", round = true, roundJoin = true),
            BrandIconShape.Path("M12 6l0 13", round = true, roundJoin = true),
            BrandIconShape.Path("M21 6l0 13", round = true, roundJoin = true),
        )
        BrandIconName.ChartBar -> listOf(
            BrandIconShape.Path("M3 3v16a2 2 0 0 0 2 2h16", round = true, roundJoin = true),
            BrandIconShape.Path("M8 17v-3", round = true, roundJoin = true),
            BrandIconShape.Path("M13 17V5", round = true, roundJoin = true),
            BrandIconShape.Path("M18 17V9", round = true, roundJoin = true),
        )
        BrandIconName.CircleCheck -> listOf(
            BrandIconShape.Path("M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
            BrandIconShape.Path("M9 12l2 2l4 -4", round = true, roundJoin = true),
        )
        BrandIconName.Check -> listOf(
            BrandIconShape.Path("M4 12l5.33 5.33l10.67 -10.67", round = true, roundJoin = true),
        )
        BrandIconName.ChevronsUpDown -> listOf(
            BrandIconShape.Path("M5 10l7 -7l7 7", round = true, roundJoin = true),
            BrandIconShape.Path("M19 14l-7 7l-7 -7", round = true, roundJoin = true),
        )
        BrandIconName.CreditCard -> listOf(
            BrandIconShape.Path("M3 5m0 3a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3z", round = true, roundJoin = true),
            BrandIconShape.Path("M3 10l18 0", round = true, roundJoin = true),
            BrandIconShape.Path("M7 15l.01 0", round = true, roundJoin = true),
            BrandIconShape.Path("M11 15l2 0", round = true, roundJoin = true),
        )
        BrandIconName.Copy -> listOf(
            BrandIconShape.Path("M8 8m0 2a2 2 0 0 1 2 -2h9a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-9a2 2 0 0 1 -2 -2z", round = true, roundJoin = true),
            BrandIconShape.Path("M16 8v-2a2 2 0 0 0 -2 -2h-9a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h2", round = true, roundJoin = true),
        )
        BrandIconName.Download -> listOf(
            BrandIconShape.Path("M3 17v2a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-2", round = true, roundJoin = true),
            BrandIconShape.Path("M6 10l6 6l6 -6", round = true, roundJoin = true),
            BrandIconShape.Path("M12 3l0 13", round = true, roundJoin = true),
        )
        BrandIconName.GraduationCap -> listOf(
            BrandIconShape.Path("M21 9.3l-9 -3.6l-9 3.6l9 3.6l9 -3.6v5.4", round = true, roundJoin = true),
            BrandIconShape.Path("M6.6 10.74v4.86a5.4 2.7 0 0 0 10.8 0v-4.86", round = true, roundJoin = true),
        )
        BrandIconName.Key -> listOf(
            BrandIconShape.Path("M16.555 3.843l3.602 3.602a2.877 2.877 0 0 1 0 4.069l-2.643 2.643a2.877 2.877 0 0 1 -4.069 0l-.301 -.301l-6.558 6.558a2 2 0 0 1 -1.239 .578l-.175 .008h-1.172a1 1 0 0 1 -.993 -.883l-.007 -.117v-1.172a2 2 0 0 1 .467 -1.284l.119 -.13l.414 -.414h2v-2h2v-2l2.144 -2.144l-.301 -.301a2.877 2.877 0 0 1 0 -4.069l2.643 -2.643a2.877 2.877 0 0 1 4.069 0z", round = true, roundJoin = true),
            BrandIconShape.Path("M15 9m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"),
        )
        BrandIconName.Logout -> listOf(
            BrandIconShape.Path("M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2", round = true, roundJoin = true),
            BrandIconShape.Path("M7 12h14l-3 -3", round = true, roundJoin = true),
            BrandIconShape.Path("M18 15l3 -3", round = true, roundJoin = true),
        )
        BrandIconName.Message -> listOf(
            BrandIconShape.Path("M18 4a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3z", round = true, roundJoin = true),
            BrandIconShape.Path("M8 9l8 0", round = true, roundJoin = true),
            BrandIconShape.Path("M8 13l6 0", round = true, roundJoin = true),
        )
        BrandIconName.DeviceDesktop -> listOf(
            BrandIconShape.Path("M3 5m0 1a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1z", round = true, roundJoin = true),
            BrandIconShape.Path("M7 20l10 0", round = true, roundJoin = true),
            BrandIconShape.Path("M9 16l0 4", round = true, roundJoin = true),
            BrandIconShape.Path("M15 16l0 4", round = true, roundJoin = true),
        )
        BrandIconName.Dots -> listOf(
            BrandIconShape.Circle(5f, 12f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(12f, 12f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(19f, 12f, 1.5f, filled = true, stroked = false),
        )
        BrandIconName.Grid -> listOf(
            BrandIconShape.Circle(5f, 5f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(12f, 5f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(19f, 5f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(5f, 12f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(12f, 12f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(19f, 12f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(5f, 19f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(12f, 19f, 1.5f, filled = true, stroked = false),
            BrandIconShape.Circle(19f, 19f, 1.5f, filled = true, stroked = false),
        )
        BrandIconName.LayoutSidebar -> listOf(
            BrandIconShape.Path("M3.5 3.5m0 2a2 2 0 0 1 2 -2h13a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-13a2 2 0 0 1 -2 -2z", round = true, roundJoin = true),
            BrandIconShape.Path("M9 3.5l0 17", round = true, roundJoin = true),
        )
        BrandIconName.Plus -> listOf(
            BrandIconShape.Path("M12 4l0 16", round = true, roundJoin = true),
            BrandIconShape.Path("M4 12l16 0", round = true, roundJoin = true),
        )
        BrandIconName.Receipt -> listOf(
            BrandIconShape.Path("M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2", round = true, roundJoin = true),
            BrandIconShape.Path("M10 8l4 0", round = true, roundJoin = true),
            BrandIconShape.Path("M10 12l4 0", round = true, roundJoin = true),
        )
        BrandIconName.FileText -> listOf(
            BrandIconShape.Path("M14 3v4a1 1 0 0 0 1 1h4", round = true, roundJoin = true),
            BrandIconShape.Path("M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z", round = true, roundJoin = true),
            BrandIconShape.Path("M9 9l1 0", round = true, roundJoin = true),
            BrandIconShape.Path("M9 13l6 0", round = true, roundJoin = true),
            BrandIconShape.Path("M9 17l6 0", round = true, roundJoin = true),
        )
        BrandIconName.Settings -> listOf(
            BrandIconShape.Path("M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z", round = true, roundJoin = true),
            BrandIconShape.Path("M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"),
        )
        BrandIconName.ShieldCheck -> listOf(
            BrandIconShape.Path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round = true, roundJoin = true),
            BrandIconShape.Path("M9 12l2 2l4 -4", round = true, roundJoin = true),
        )
        BrandIconName.Shield -> listOf(
            BrandIconShape.Path("M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3", round = true, roundJoin = true),
        )
        BrandIconName.Star -> listOf(
            BrandIconShape.Path("M12 2.8 L14.12 9.09 L20.75 9.16 L15.42 13.11 L17.41 19.44 L12 15.6 L6.59 19.44 L8.58 13.11 L3.25 9.16 L9.88 9.09 Z", round = true, roundJoin = true),
        )
        BrandIconName.Upload -> listOf(
            BrandIconShape.Path("M12 17V3", round = true, roundJoin = true),
            BrandIconShape.Path("M6 9l6 -6l6 6", round = true, roundJoin = true),
            BrandIconShape.Path("M3 21h18", round = true, roundJoin = true),
        )
        BrandIconName.User -> listOf(
            BrandIconShape.Path("M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"),
            BrandIconShape.Path("M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2", round = true, roundJoin = true),
        )
        BrandIconName.Webhook -> listOf(
            BrandIconShape.Circle(17f, 17f, 3f),
            BrandIconShape.Circle(6.5f, 10f, 3.5f),
            BrandIconShape.Circle(14f, 6f, 3f),
            BrandIconShape.Path("M9.5 8.7 L11.8 4.3", round = true),
            BrandIconShape.Path("M8.5 12.8 L14.7 16.4", round = true),
            BrandIconShape.Path("M15.7 8.2 L17 14", round = true),
        )
        BrandIconName.ChevronRight -> listOf(
            BrandIconShape.Path("M7.5 3 L16.5 12 L7.5 21", round = true, roundJoin = true),
        )
        BrandIconName.ChevronDown -> listOf(
            BrandIconShape.Path("M21 7.5 L12 16.5 L3 7.5", round = true, roundJoin = true),
        )
        BrandIconName.ChevronUp -> listOf(
            BrandIconShape.Path("M3 16.5 L12 7.5 L21 16.5", round = true, roundJoin = true),
        )
        BrandIconName.Info -> listOf(
            BrandIconShape.Circle(12f, 12f, 9f),
            BrandIconShape.Path("M12 7.5l0 .01", round = true),
            BrandIconShape.Path("M12 11l0 5", round = true),
        )
        BrandIconName.AlertTriangle -> listOf(
            BrandIconShape.Path("M12 3 L21 20 H3 Z", round = true, roundJoin = true),
            BrandIconShape.Path("M12 9l0 5", round = true),
            BrandIconShape.Path("M12 17l0 .01", round = true),
        )
        BrandIconName.AlertError -> listOf(
            BrandIconShape.Path("M8 3h8l5 5v8l-5 5h-8l-5 -5v-8z", round = true, roundJoin = true),
            BrandIconShape.Path("M9 9l6 6M15 9l-6 6", round = true),
        )
        BrandIconName.Connection -> listOf(
            BrandIconShape.Path("M9 3l0 3M15 3l0 3", round = true),
            BrandIconShape.Path("M6.5 6h11v2.5a5.5 5.5 0 0 1 -11 0z", round = true, roundJoin = true),
            BrandIconShape.Path("M12 14l0 2l-2 2.5h4l-2 2.5", round = true, roundJoin = true),
        )
        BrandIconName.Package -> listOf(
            BrandIconShape.Path("M12 3l8 4.5v9l-8 4.5l-8 -4.5v-9z", round = true, roundJoin = true),
            BrandIconShape.Path("M12 12l8 -4.5M12 12l0 9M12 12l-8 -4.5", round = true, roundJoin = true),
        )
        BrandIconName.Archive -> listOf(
            BrandIconShape.Path("M4 4a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1z", round = true, roundJoin = true),
            BrandIconShape.Path("M5 9l0 9a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2l0 -9", round = true, roundJoin = true),
            BrandIconShape.Path("M10 13l4 0", round = true),
        )
        BrandIconName.Database -> listOf(
            BrandIconShape.Path("M3 6a9 3 0 1 0 18 0a9 3 0 1 0 -18 0", round = true, roundJoin = true),
            BrandIconShape.Path("M3 6l0 6a9 3 0 0 0 18 0l0 -6", round = true, roundJoin = true),
            BrandIconShape.Path("M3 12l0 6a9 3 0 0 0 18 0l0 -6", round = true, roundJoin = true),
        )
        BrandIconName.Building -> listOf(
            BrandIconShape.Path("M5 21l0 -16a2 2 0 0 1 2 -2l10 0a2 2 0 0 1 2 2l0 16", round = true, roundJoin = true),
            BrandIconShape.Path("M3 21l18 0", round = true),
            BrandIconShape.Path("M9 8l.01 0M15 8l.01 0M9 12l.01 0M15 12l.01 0M9 16l.01 0M15 16l.01 0", round = true),
        )
        BrandIconName.Send -> listOf(
            BrandIconShape.Path("M3 21l18 -9l-18 -9l0 7.31l11.25 1.69l-11.25 1.69z", round = true, roundJoin = true),
        )
        BrandIconName.ExternalLink -> listOf(
            BrandIconShape.Path("M19 13l0 6a2 2 0 0 1 -2 2l-10 0a2 2 0 0 1 -2 -2l0 -10a2 2 0 0 1 2 -2l6 0", round = true, roundJoin = true),
            BrandIconShape.Path("M15 3l6 0l0 6", round = true, roundJoin = true),
            BrandIconShape.Path("M9 15l12 -12", round = true),
        )
        BrandIconName.Gavel -> listOf(
            BrandIconShape.Path("M19 8l-3 -3l-8 8l3 3z", round = true, roundJoin = true),
            BrandIconShape.Path("M11 13l-5 5", round = true),
            BrandIconShape.Path("M3 21l8 0", round = true),
        )
        BrandIconName.Inbox -> listOf(
            BrandIconShape.Path("M3 12L6.45 5.11A2 2 0 0 1 8.24 4H15.76A2 2 0 0 1 17.55 5.11L21 12V18A2 2 0 0 1 19 20H5A2 2 0 0 1 3 18Z", round = true, roundJoin = true),
            BrandIconShape.Path("M21 12h-5l-2 3h-4l-2 -3H3", round = true, roundJoin = true),
        )
        BrandIconName.Library -> listOf(
            BrandIconShape.Path("M4 21l0 -15a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 15", round = true, roundJoin = true),
            BrandIconShape.Path("M10 21l0 -17a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 17", round = true, roundJoin = true),
            BrandIconShape.Path("M16 21l0 -13a1 1 0 0 1 1 -1l2 0a1 1 0 0 1 1 1l0 13", round = true, roundJoin = true),
            BrandIconShape.Path("M3 21l18 0", round = true),
        )
        BrandIconName.Calendar -> listOf(
            BrandIconShape.Path("M5 6h14a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2z", round = true, roundJoin = true),
            BrandIconShape.Path("M3 10 H21", round = true),
            BrandIconShape.Path("M8 4 V8", round = true),
            BrandIconShape.Path("M16 4 V8", round = true),
        )
        BrandIconName.Target -> listOf(
            BrandIconShape.Circle(12f, 12f, 9f),
            BrandIconShape.Circle(12f, 12f, 5f),
            BrandIconShape.Circle(12f, 12f, 1f),
        )
        BrandIconName.Languages -> listOf(
            BrandIconShape.Circle(12f, 12f, 9f),
            BrandIconShape.Path("M3 12l18 0", round = true),
            BrandIconShape.Path("M12 3a14 14 0 0 1 0 18a14 14 0 0 1 0 -18", round = true, roundJoin = true),
        )
    }
