export const entryPoints = {
  // Atoms
  'accordion':           'src/stories/atoms/Accordion/Accordion.tsx',
  'async-multi-select':  'src/stories/atoms/AsyncMultiSelect/AsyncMultiSelect.tsx',
  'async-select':        'src/stories/atoms/AsyncSelect/AsyncSelect.tsx',
  'arrow':               'src/stories/atoms/Arrow/Arrow.tsx',
  'description-list':    'src/stories/atoms/DescriptionList/DescriptionList.tsx',
  'avatar':              'src/stories/atoms/Avatar/Avatar.tsx',
  'button':              'src/stories/atoms/Button/Button.tsx',
  'carousel':            'src/stories/atoms/Carousel/Carousel.tsx',
  'checkbox':            'src/stories/atoms/Checkbox/Checkbox.tsx',
  'radio':               'src/stories/atoms/Radio/Radio.tsx',
  'icon':                'src/stories/atoms/Icon/Icon.tsx',
  'hamburger':           'src/stories/atoms/Hamburger/Hamburger.tsx',
  'fieldset':            'src/stories/atoms/Fieldset/Fieldset.tsx',
  'heading':             'src/stories/atoms/Heading/Heading.tsx',
  'input':               'src/stories/atoms/Input/Input.tsx',
  'otp-input':           'src/stories/atoms/OtpInput/OtpInput.tsx',
  'input-phone':         'src/stories/atoms/InputPhone/InputPhone.tsx',
  'label':               'src/stories/atoms/Label/Label.tsx',
  'link':                'src/stories/atoms/Link/Link.tsx',
  'list':                'src/stories/atoms/List/List.tsx',
  'logo':                'src/stories/atoms/Logo/Logo.tsx',
  'dots-button':         'src/stories/atoms/DotsButton/DotsButton.tsx',
  'paragraph':           'src/stories/atoms/Paragraph/Paragraph.tsx',
  'progress-bar':        'src/stories/atoms/ProgressBar/ProgressBar.tsx',
  'popover':             'src/stories/atoms/Popover/Popover.tsx',
  'multi-select':        'src/stories/atoms/MultiSelect/MultiSelect.tsx',
  'select':              'src/stories/atoms/Select/Select.tsx',
  'time-select':         'src/stories/atoms/TimeSelect/TimeSelect.tsx',
  'tag':                 'src/stories/atoms/Tag/Tag.tsx',
  'textarea':            'src/stories/atoms/Textarea/Textarea.tsx',
  'hero-video':          'src/stories/atoms/HeroVideo/HeroVideo.tsx',
  'highlight':           'src/stories/atoms/Highlight/Highlight.tsx',
  'skip-link':           'src/stories/atoms/SkipLink/SkipLink.tsx',
  'spinner':             'src/stories/atoms/Spinner/Spinner.tsx',
  'switcher':            'src/stories/atoms/Switcher/Switcher.tsx',
  'tabs':                'src/stories/atoms/Tabs/Tabs.tsx',
  'visually-hidden':     'src/stories/atoms/VisuallyHidden/VisuallyHidden.tsx',
  'number-input':        'src/stories/atoms/NumberInput/NumberInput.tsx',
  'file-upload':         'src/stories/atoms/FileUpload/FileUpload.tsx',
  'number-badge':        'src/stories/atoms/NumberBadge/NumberBadge.tsx',
  'message-bubble':      'src/stories/atoms/MessageBubble/MessageBubble.tsx',
  'typing-indicator':    'src/stories/atoms/TypingIndicator/TypingIndicator.tsx',
  // Molecules
  'alert':                   'src/stories/molecules/Alert/Alert.tsx',
  'async-multi-select-field': 'src/stories/molecules/AsyncMultiSelectField/AsyncMultiSelectField.tsx',
  'async-select-field':  'src/stories/molecules/AsyncSelectField/AsyncSelectField.tsx',
  'breadcrumb':          'src/stories/molecules/Breadcrumb/Breadcrumb.tsx',
  'pagination':          'src/stories/molecules/Pagination/Pagination.tsx',
  'prev-next-nav':       'src/stories/molecules/PrevNextNav/PrevNextNav.tsx',
  'table':               'src/stories/molecules/Table/Table.tsx',
  'context-menu':        'src/stories/molecules/ContextMenu/ContextMenu.tsx',
  'card':                'src/stories/molecules/Card/Card.tsx',
  'project-card':        'src/stories/molecules/ProjectCard/ProjectCard.tsx',
  'card-split':          'src/stories/molecules/CardSplit/CardSplit.tsx',
  'card-square':         'src/stories/molecules/CardSquare/CardSquare.tsx',
  'checkbox-field':      'src/stories/molecules/CheckboxField/CheckboxField.tsx',
  'radio-field':         'src/stories/molecules/RadioField/RadioField.tsx',
  'switcher-field':      'src/stories/molecules/SwitcherField/SwitcherField.tsx',
  'form':                'src/stories/molecules/Form/Form.tsx',
  'input-field':         'src/stories/molecules/InputField/InputField.tsx',
  'otp-field':           'src/stories/molecules/OtpField/OtpField.tsx',
  'multi-select-field':  'src/stories/molecules/MultiSelectField/MultiSelectField.tsx',
  'select-field':        'src/stories/molecules/SelectField/SelectField.tsx',
  'input-phone-field':   'src/stories/molecules/InputPhoneField/InputPhoneField.tsx',
  'textarea-field':      'src/stories/molecules/TextareaField/TextareaField.tsx',
  'org-switcher':        'src/stories/molecules/OrgSwitcher/OrgSwitcher.tsx',
  'user-menu':           'src/stories/molecules/UserMenu/UserMenu.tsx',
  'modal':               'src/stories/molecules/Modal/Modal.tsx',
  'sidebar-nav':         'src/stories/molecules/SidebarNav/SidebarNav.tsx',
  'date-picker':         'src/stories/molecules/DatePicker/DatePicker.tsx',
  'date-picker-field':   'src/stories/molecules/DatePickerField/DatePickerField.tsx',
  'date-time-field':     'src/stories/molecules/DateTimeField/DateTimeField.tsx',
  'time-field':          'src/stories/molecules/TimeField/TimeField.tsx',
  'calendar':            'src/stories/molecules/Calendar/Calendar.tsx',
  'calendar-planner':    'src/stories/molecules/CalendarPlanner/CalendarPlanner.tsx',
  'calendar-roster':     'src/stories/molecules/CalendarRoster/CalendarRoster.tsx',
  'empty-state':         'src/stories/molecules/EmptyState/EmptyState.tsx',
  'password-field':      'src/stories/molecules/PasswordField/PasswordField.tsx',
  'toaster':             'src/stories/molecules/Toast/Toaster.tsx',
  'number-input-field':  'src/stories/molecules/NumberInputField/NumberInputField.tsx',
  'file-upload-field':   'src/stories/molecules/FileUploadField/FileUploadField.tsx',
  'user-message':        'src/stories/molecules/UserMessage/UserMessage.tsx',
  'assistant-message':   'src/stories/molecules/AssistantMessage/AssistantMessage.tsx',
  'model-selector':      'src/stories/molecules/ModelSelector/ModelSelector.tsx',
  'message-composer':    'src/stories/molecules/MessageComposer/MessageComposer.tsx',
  // Sections
  'app-shell':           'src/stories/sections/AppShell/AppShell.tsx',
  'sidebar':             'src/stories/sections/Sidebar/Sidebar.tsx',
  // Organisms
  'login-form':          'src/stories/organisms/LoginForm/LoginForm.tsx',
  'project-carousel':    'src/stories/organisms/ProjectCarousel/ProjectCarousel.tsx',
  'project-grid':        'src/stories/organisms/ProjectGrid/ProjectGrid.tsx',
  'review-carousel':     'src/stories/organisms/ReviewCarousel/ReviewCarousel.tsx',
  'steps':               'src/stories/organisms/Steps/Steps.tsx',
  'conversation-thread': 'src/stories/organisms/ConversationThread/ConversationThread.tsx',
};

export const clientComponents = new Set([
  'alert', 'accordion', 'async-multi-select', 'async-multi-select-field', 'async-select', 'async-select-field',
  'button', 'carousel', 'checkbox', 'radio', 'switcher', 'hamburger', 'hero-video', 'input',
  'input-phone', 'link', 'multi-select', 'select', 'time-select', 'textarea', 'checkbox-field', 'radio-field', 'switcher-field', 'form',
  'input-field', 'otp-input', 'otp-field', 'multi-select-field', 'select-field', 'input-phone-field', 'textarea-field', 'login-form', 'project-carousel', 'project-grid',
  'dots-button', 'context-menu', 'popover', 'pagination', 'table',
  'sidebar',
  'app-shell',
  'modal',
  'org-switcher', 'user-menu', 'sidebar-nav',
  'tabs',
  'date-picker',
  'date-picker-field',
  'date-time-field',
  'time-field',
  'calendar',
  'calendar-planner',
  'calendar-roster',
  'password-field',
  'toaster',
  'number-input',
  'number-input-field',
  'file-upload',
  'file-upload-field',
  'message-composer',
  'conversation-thread',
]);
