export const entryPoints = {
  // Atoms
  'accordion':           'src/stories/atoms/Accordion/Accordion.tsx',
  'arrow':               'src/stories/atoms/Arrow/Arrow.tsx',
  'avatar':              'src/stories/atoms/Avatar/Avatar.tsx',
  'button':              'src/stories/atoms/Button/Button.tsx',
  'carousel':            'src/stories/atoms/Carousel/Carousel.tsx',
  'checkbox':            'src/stories/atoms/Checkbox/Checkbox.tsx',
  'radio':               'src/stories/atoms/Radio/Radio.tsx',
  'chevron':             'src/stories/atoms/Chevron/Chevron.tsx',
  'hamburger':           'src/stories/atoms/Hamburger/Hamburger.tsx',
  'heading':             'src/stories/atoms/Heading/Heading.tsx',
  'input':               'src/stories/atoms/Input/Input.tsx',
  'input-phone':         'src/stories/atoms/InputPhone/InputPhone.tsx',
  'label':               'src/stories/atoms/Label/Label.tsx',
  'link':                'src/stories/atoms/Link/Link.tsx',
  'list':                'src/stories/atoms/List/List.tsx',
  'logo':                'src/stories/atoms/Logo/Logo.tsx',
  'dots-button':         'src/stories/atoms/DotsButton/DotsButton.tsx',
  'paragraph':           'src/stories/atoms/Paragraph/Paragraph.tsx',
  'popover':             'src/stories/atoms/Popover/Popover.tsx',
  'select':              'src/stories/atoms/Select/Select.tsx',
  'tag':                 'src/stories/atoms/Tag/Tag.tsx',
  'textarea':            'src/stories/atoms/Textarea/Textarea.tsx',
  'hero-video':          'src/stories/atoms/HeroVideo/HeroVideo.tsx',
  'highlight':           'src/stories/atoms/Highlight/Highlight.tsx',
  'skip-link':           'src/stories/atoms/SkipLink/SkipLink.tsx',
  'tabs':                'src/stories/atoms/Tabs/Tabs.tsx',
  'visually-hidden':     'src/stories/atoms/VisuallyHidden/VisuallyHidden.tsx',
  // Molecules
  'breadcrumb':          'src/stories/molecules/Breadcrumb/Breadcrumb.tsx',
  'pagination':          'src/stories/molecules/Pagination/Pagination.tsx',
  'table':               'src/stories/molecules/Table/Table.tsx',
  'context-menu':        'src/stories/molecules/ContextMenu/ContextMenu.tsx',
  'card':                'src/stories/molecules/Card/Card.tsx',
  'project-card':        'src/stories/molecules/ProjectCard/ProjectCard.tsx',
  'card-split':          'src/stories/molecules/CardSplit/CardSplit.tsx',
  'card-square':         'src/stories/molecules/CardSquare/CardSquare.tsx',
  'checkbox-field':      'src/stories/molecules/CheckboxField/CheckboxField.tsx',
  'radio-field':         'src/stories/molecules/RadioField/RadioField.tsx',
  'form':                'src/stories/molecules/Form/Form.tsx',
  'input-field':         'src/stories/molecules/InputField/InputField.tsx',
  'select-field':        'src/stories/molecules/SelectField/SelectField.tsx',
  'input-phone-field':   'src/stories/molecules/InputPhoneField/InputPhoneField.tsx',
  'textarea-field':      'src/stories/molecules/TextareaField/TextareaField.tsx',
  'org-switcher':        'src/stories/molecules/OrgSwitcher/OrgSwitcher.tsx',
  'user-menu':           'src/stories/molecules/UserMenu/UserMenu.tsx',
  'modal':               'src/stories/molecules/Modal/Modal.tsx',
  'sidebar-nav':         'src/stories/molecules/SidebarNav/SidebarNav.tsx',
  // Sections
  'app-shell':           'src/stories/sections/AppShell/AppShell.tsx',
  'sidebar':             'src/stories/sections/Sidebar/Sidebar.tsx',
  // Organisms
  'project-carousel':    'src/stories/organisms/ProjectCarousel/ProjectCarousel.tsx',
  'project-grid':        'src/stories/organisms/ProjectGrid/ProjectGrid.tsx',
  'review-carousel':     'src/stories/organisms/ReviewCarousel/ReviewCarousel.tsx',
  'steps':               'src/stories/organisms/Steps/Steps.tsx',
};

export const clientComponents = new Set([
  'accordion', 'button', 'carousel', 'checkbox', 'radio', 'hamburger', 'hero-video', 'input',
  'input-phone', 'link', 'select', 'textarea', 'checkbox-field', 'radio-field', 'form',
  'input-field', 'select-field', 'input-phone-field', 'textarea-field', 'project-carousel', 'project-grid',
  'dots-button', 'context-menu', 'popover', 'pagination', 'table',
  'sidebar',
  'app-shell',
  'modal',
  'org-switcher', 'user-menu', 'sidebar-nav',
  'tabs',
]);
