export const entryPoints = {
  // Atoms
  'accordion':           'src/stories/atoms/Accordion/Accordion.tsx',
  'async-multi-select':  'src/stories/atoms/AsyncMultiSelect/AsyncMultiSelect.tsx',
  'async-select':        'src/stories/atoms/AsyncSelect/AsyncSelect.tsx',
  'arrow':               'src/stories/atoms/Arrow/Arrow.tsx',
  'description-list':    'src/stories/atoms/DescriptionList/DescriptionList.tsx',
  'avatar':              'src/stories/atoms/Avatar/Avatar.tsx',
  'button':              'src/stories/atoms/Button/Button.tsx',
  'checkbox':            'src/stories/atoms/Checkbox/Checkbox.tsx',
  'container':           'src/stories/atoms/Container/Container.tsx',
  'columns':             'src/stories/atoms/Columns/Columns.tsx',
  'stack':               'src/stories/atoms/Stack/Stack.tsx',
  'inline':              'src/stories/atoms/Inline/Inline.tsx',
  'radio':               'src/stories/atoms/Radio/Radio.tsx',
  'icon':                'src/stories/atoms/Icon/Icon.tsx',
  'menu-button':         'src/stories/atoms/MenuButton/MenuButton.tsx',
  'code':                'src/stories/atoms/Code/Code.tsx',
  'fieldset':            'src/stories/atoms/Fieldset/Fieldset.tsx',
  'figure':              'src/stories/atoms/Figure/Figure.tsx',
  'heading':             'src/stories/atoms/Heading/Heading.tsx',
  'input':               'src/stories/atoms/Input/Input.tsx',
  'otp-input':           'src/stories/atoms/OtpInput/OtpInput.tsx',
  'input-phone':         'src/stories/atoms/InputPhone/InputPhone.tsx',
  'label':               'src/stories/atoms/Label/Label.tsx',
  'link':                'src/stories/atoms/Link/Link.tsx',
  'list':                'src/stories/atoms/List/List.tsx',
  'logo':                'src/stories/atoms/Logo/Logo.tsx',
  'logomark':            'src/stories/atoms/Logomark/index.ts',
  'dots-button':         'src/stories/atoms/DotsButton/DotsButton.tsx',
  'paragraph':           'src/stories/atoms/Paragraph/Paragraph.tsx',
  'progress-bar':        'src/stories/atoms/ProgressBar/ProgressBar.tsx',
  'popover':             'src/stories/atoms/Popover/Popover.tsx',
  'multi-select':        'src/stories/atoms/MultiSelect/MultiSelect.tsx',
  'select':              'src/stories/atoms/Select/Select.tsx',
  'radio-group':         'src/stories/atoms/RadioGroup/RadioGroup.tsx',
  'separator':           'src/stories/atoms/Separator/Separator.tsx',
  'time-select':         'src/stories/atoms/TimeSelect/TimeSelect.tsx',
  'tag':                 'src/stories/atoms/Tag/Tag.tsx',
  'text':                'src/stories/atoms/Text/Text.tsx',
  'sparkline':           'src/stories/atoms/Sparkline/Sparkline.tsx',
  'star-rating':         'src/stories/atoms/StarRating/StarRating.tsx',
  'toggle':              'src/stories/atoms/Toggle/Toggle.tsx',
  'toggle-group':        'src/stories/atoms/ToggleGroup/ToggleGroup.tsx',
  'collapsible':         'src/stories/atoms/Collapsible/Collapsible.tsx',
  'scroll-area':         'src/stories/atoms/ScrollArea/ScrollArea.tsx',
  'slider':              'src/stories/atoms/Slider/Slider.tsx',
  'kbd':                 'src/stories/atoms/Kbd/Kbd.tsx',
  'textarea':            'src/stories/atoms/Textarea/Textarea.tsx',
  'skip-link':           'src/stories/atoms/SkipLink/SkipLink.tsx',
  'spinner':             'src/stories/atoms/Spinner/Spinner.tsx',
  'switcher':            'src/stories/atoms/Switcher/Switcher.tsx',
  'tabs':                'src/stories/atoms/Tabs/Tabs.tsx',
  'visually-hidden':     'src/stories/atoms/VisuallyHidden/VisuallyHidden.tsx',
  'error-boundary':      'src/stories/atoms/ErrorBoundary/ErrorBoundary.tsx',
  'number-input':        'src/stories/atoms/NumberInput/NumberInput.tsx',
  'file-upload':         'src/stories/atoms/FileUpload/FileUpload.tsx',
  'number-badge':        'src/stories/atoms/NumberBadge/NumberBadge.tsx',
  'message-bubble':      'src/stories/atoms/MessageBubble/MessageBubble.tsx',
  'typing-indicator':    'src/stories/atoms/TypingIndicator/TypingIndicator.tsx',
  'skeleton':            'src/stories/atoms/Skeleton/Skeleton.tsx',
  'tooltip':             'src/stories/atoms/Tooltip/Tooltip.tsx',
  // Molecules
  'alert':                   'src/stories/molecules/Alert/Alert.tsx',
  'async-multi-select-field': 'src/stories/molecules/AsyncMultiSelectField/AsyncMultiSelectField.tsx',
  'async-select-field':  'src/stories/molecules/AsyncSelectField/AsyncSelectField.tsx',
  'breadcrumb':          'src/stories/molecules/Breadcrumb/Breadcrumb.tsx',
  'pagination':          'src/stories/molecules/Pagination/Pagination.tsx',
  'prev-next-nav':       'src/stories/molecules/PrevNextNav/PrevNextNav.tsx',
  'consent':             'src/stories/molecules/Consent/Consent.tsx',
  'table':               'src/stories/molecules/Table/Table.tsx',
  'context-menu':        'src/stories/molecules/ContextMenu/ContextMenu.tsx',
  'card':                'src/stories/molecules/Card/Card.tsx',
  'carousel':            'src/stories/molecules/Carousel/Carousel.tsx',
  'steps':               'src/stories/organisms/Steps/Steps.tsx',
  'project-card':        'src/stories/molecules/ProjectCard/ProjectCard.tsx',
  'code-block':          'src/stories/molecules/CodeBlock/CodeBlock.tsx',
  'checkbox-field':      'src/stories/molecules/CheckboxField/CheckboxField.tsx',
  'radio-field':         'src/stories/molecules/RadioField/RadioField.tsx',
  'switcher-field':      'src/stories/molecules/SwitcherField/SwitcherField.tsx',
  'form':                'src/stories/molecules/Form/Form.tsx',
  'input-field':         'src/stories/molecules/InputField/InputField.tsx',
  'otp-field':           'src/stories/molecules/OtpField/OtpField.tsx',
  'multi-select-field':  'src/stories/molecules/MultiSelectField/MultiSelectField.tsx',
  'select-field':        'src/stories/molecules/SelectField/SelectField.tsx',
  'input-phone-field':   'src/stories/molecules/InputPhoneField/InputPhoneField.tsx',
  'textarea-field':      'src/stories/molecules/TextareaField/TextareaField.tsx',
  'org-switcher':        'src/stories/molecules/OrgSwitcher/OrgSwitcher.tsx',
  'user-menu':           'src/stories/molecules/UserMenu/UserMenu.tsx',
  'modal':               'src/stories/molecules/Modal/Modal.tsx',
  'sidebar-nav':         'src/stories/molecules/SidebarNav/SidebarNav.tsx',
  'tree-view':           'src/stories/molecules/TreeView/TreeView.tsx',
  'annotation-thread':   'src/stories/organisms/AnnotationThread/AnnotationThread.tsx',
  'date-picker':         'src/stories/molecules/DatePicker/DatePicker.tsx',
  'date-picker-field':   'src/stories/molecules/DatePickerField/DatePickerField.tsx',
  'date-time-field':     'src/stories/molecules/DateTimeField/DateTimeField.tsx',
  'time-field':          'src/stories/molecules/TimeField/TimeField.tsx',
  'calendar':            'src/stories/molecules/Calendar/Calendar.tsx',
  'calendar-planner':    'src/stories/molecules/CalendarPlanner/CalendarPlanner.tsx',
  'calendar-roster':     'src/stories/molecules/CalendarRoster/CalendarRoster.tsx',
  'empty-state':         'src/stories/molecules/EmptyState/EmptyState.tsx',
  'password-field':      'src/stories/molecules/PasswordField/PasswordField.tsx',
  'toaster':             'src/stories/molecules/Toast/Toaster.tsx',
  'toast':               'src/stories/molecules/Toast/toast.ts',
  'number-input-field':  'src/stories/molecules/NumberInputField/NumberInputField.tsx',
  'file-upload-field':   'src/stories/molecules/FileUploadField/FileUploadField.tsx',
  'user-message':        'src/stories/molecules/UserMessage/UserMessage.tsx',
  'assistant-message':   'src/stories/molecules/AssistantMessage/AssistantMessage.tsx',
  'message-composer':      'src/stories/molecules/MessageComposer/MessageComposer.tsx',
  'conversation-list':     'src/stories/molecules/ConversationList/ConversationList.tsx',
  'command-palette':     'src/stories/molecules/CommandPalette/CommandPalette.tsx',
  'form-field':          'src/stories/molecules/FormField/FormField.tsx',
  'image-crop-dialog':   'src/stories/molecules/ImageCropDialog/ImageCropDialog.tsx',
  'menu':                'src/stories/molecules/Menu/Menu.tsx',
  'sheet':               'src/stories/molecules/Sheet/Sheet.tsx',
  'app-launcher':        'src/stories/molecules/AppLauncher/AppLauncher.tsx',
  'site-nav':            'src/stories/molecules/SiteNav/SiteNav.tsx',
  'language-switcher':   'src/stories/molecules/LanguageSwitcher/LanguageSwitcher.tsx',
  'theme-switcher':      'src/stories/molecules/ThemeSwitcher/ThemeSwitcher.tsx',
  'dropdown-field':      'src/stories/molecules/DropdownField/DropdownField.tsx',
  'notification-button': 'src/stories/molecules/NotificationButton/NotificationButton.tsx',
  'prose':               'src/stories/molecules/Prose/Prose.tsx',
  'table-of-contents':   'src/stories/molecules/TableOfContents/TableOfContents.tsx',
  'docs-search':         'src/stories/molecules/DocsSearch/DocsSearch.tsx',
  'stat-tile':           'src/stories/molecules/StatTile/StatTile.tsx',
  'copy-button':         'src/stories/molecules/CopyButton/CopyButton.tsx',
  'confirm-dialog':      'src/stories/molecules/ConfirmDialog/ConfirmDialog.tsx',
  'search-form':         'src/stories/molecules/SearchForm/SearchForm.tsx',
  // Sections
  'app-shell':           'src/stories/sections/AppShell/AppShell.tsx',
  'app-header':          'src/stories/sections/AppHeader/AppHeader.tsx',
  'sidebar':             'src/stories/sections/Sidebar/Sidebar.tsx',
  'site-header':         'src/stories/sections/SiteHeader/SiteHeader.tsx',
  'app-root':            'src/stories/sections/AppRoot/AppRoot.tsx',
  'page-intro':          'src/stories/molecules/PageIntro/PageIntro.tsx',
  'site-shell':          'src/stories/sections/SiteShell/SiteShell.tsx',
  'legal-footer':        'src/stories/sections/LegalFooter/LegalFooter.tsx',
  'hero':                'src/stories/sections/Hero/Hero.tsx',
  'site-footer':         'src/stories/sections/SiteFooter/SiteFooter.tsx',
  'highlight':           'src/stories/sections/Highlight/Highlight.tsx',
  // Templates
  'not-found-page':      'src/stories/templates/NotFoundPage/NotFoundPage.tsx',
  'error-page':          'src/stories/templates/ErrorPage/ErrorPage.tsx',
  'chat-shell':          'src/stories/templates/ChatShell/ChatShell.tsx',
  // Organisms
  'data-table':          'src/stories/organisms/DataTable/DataTable.tsx',
  'conversation-thread': 'src/stories/organisms/ConversationThread/ConversationThread.tsx',
  'chart':               'src/stories/organisms/Chart/Chart.tsx',
};

export const clientComponents = new Set([
  'alert', 'accordion', 'async-multi-select', 'async-multi-select-field', 'async-select', 'async-select-field', 'code-block',
  'button', 'checkbox', 'radio', 'radio-group', 'switcher', 'menu-button', 'input',
  'input-phone', 'link', 'multi-select', 'select', 'time-select', 'textarea', 'checkbox-field', 'radio-field', 'switcher-field', 'form',
  'input-field', 'otp-input', 'otp-field', 'multi-select-field', 'select-field', 'input-phone-field', 'textarea-field', 'dots-button', 'context-menu', 'popover', 'pagination', 'table',
  'steps',
  'app-shell', 'error-boundary', 'not-found-page', 'error-page',
  'avatar',
  'card',
  'carousel',
  'project-card',
  'app-header',
  'modal',
  'org-switcher', 'user-menu', 'sidebar-nav',
  'tabs',
  'date-picker',
  'date-picker-field',
  'date-time-field',
  'time-field',
  'calendar',
  'calendar-planner',
  'calendar-roster',
  'password-field',
  'toaster',
  'toast',
  'number-input',
  'number-input-field',
  'file-upload',
  'file-upload-field',
  'message-composer',
  'tooltip',
  'command-palette',
  'form-field',
  'image-crop-dialog',
  'menu',
  'sheet',
  'consent',
  'app-launcher',
  'data-table',
  'conversation-thread',
  'chart',
  'site-header',
  'language-switcher',
  'theme-switcher',
  'dropdown-field',
  'notification-button',
  'docs-search',
  'copy-button',
  'confirm-dialog',
  'search-form',
  'star-rating',
  'toggle',
  'toggle-group',
  'collapsible',
  'scroll-area',
  'slider',
  'tree-view',
]);
