// Do not edit directly, this file was auto-generated by Style Dictionary (sd.config.mjs). Run `pnpm build:tokens`.

package com.studiolxd.brand.tokens

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing
import androidx.compose.animation.core.LinearEasing
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

/** Colores primitivos, de marca y rellenos universales: el mismo valor en superficie clara y oscura. */
object BrandColors {
    /** Token `color.primary` — Primary brand color — used ~50% of the time */
    val primary = Color(0xFF111E30)
    /** Token `color.accent-1` — Accent 1 brand color — used ~20% of the time */
    val accent1 = Color(0xFFBAABFF)
    /** Token `color.accent-2` — Accent 2 brand color — used ~20% of the time */
    val accent2 = Color(0xFFFFCD00)
    /** Token `color.support-1` — Support 1 brand color — used ~5% of the time */
    val support1 = Color(0xFF20E38E)
    /** Token `color.support-2` — Support 2 brand color — used ~5% of the time */
    val support2 = Color(0xFFF05E1C)
    /** Token `color.error-fill` — Error — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto */
    val errorFill = Color(0xFFB30000)
    /** Token `color.error-fill-text` — Error — contenido sobre error-fill */
    val errorFillText = Color(0xFFFFFFFF)
    /** Token `color.success-fill` — Success — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto */
    val successFill = Color(0xFF006616)
    /** Token `color.success-fill-text` — Success — contenido sobre success-fill */
    val successFillText = Color(0xFFFFFFFF)
    /** Token `color.warning-fill` — Aviso — fondo sólido universal (igual en superficie clara y oscura). El amarillo de marca, aquí como rol de feedback. Nunca como color de texto */
    val warningFill = Color(0xFFFFCD00)
    /** Token `color.warning-fill-text` — Aviso — contenido sobre warning-fill: el prusia (11,17:1, AAA). El rol solo tiene estos dos tokens, a propósito: ver Foundations › Colores */
    val warningFillText = Color(0xFF111E30)
    /** Token `color.destructive-fill` — Destructive — fondo sólido universal (igual en superficie clara y oscura). Nunca como color de texto */
    val destructiveFill = Color(0xFFB30000)
    /** Token `color.destructive-fill-text` — Destructive — contenido sobre destructive-fill */
    val destructiveFillText = Color(0xFFFFFFFF)
    /** Token `color.white` — Pure white */
    val white = Color(0xFFFFFFFF)
    /** Token `color.black` — Pure black */
    val black = Color(0xFF000000)
    /** Token `color.grey-lightest` — Superficie clara secundaria: bloque de código, kbd, burbujas, pie de tabla. Encima, texto prusia o grey-darkest */
    val greyLightest = Color(0xFFF2F2F2)
    /** Token `color.grey-light` — Bordes, dividers, separadores */
    val greyLight = Color(0xFFD0D0D0)
    /** Token `color.grey-dark` — Iconos de acción secundarios y controles deshabilitados. No es un gris de texto: todo texto va en prusia o grey-darkest */
    val greyDark = Color(0xFF6B6B6B)
    /** Token `color.grey-darkest` — Texto secundario y placeholder en superficie clara (AAA sobre blanco) */
    val greyDarkest = Color(0xFF4A4A4A)
    /** Token `color.prussian` — Brand prussian */
    val prussian = Color(0xFF111E30)
    /** Token `color.lavender` — Brand lavender */
    val lavender = Color(0xFFBAABFF)
    /** Token `color.yellow` — Brand yellow */
    val yellow = Color(0xFFFFCD00)
    /** Token `color.emerald` — Brand emerald */
    val emerald = Color(0xFF20E38E)
    /** Token `color.cayenne` — Brand cayenne */
    val cayenne = Color(0xFFF05E1C)
    /** Token `color.red` — System red — base (AAA sobre blanco; fill universal de error/destructive) */
    val red = Color(0xFFB30000)
    /** Token `color.red-light` — System red light — SOLO texto/icono/borde sobre prussian, nunca como fondo */
    val redLight = Color(0xFFFF8585)
    /** Token `color.green` — System green — base (AAA sobre blanco; fill universal de success) */
    val green = Color(0xFF006616)
    /** Token `color.green-light` — System green light — SOLO texto/icono/borde sobre prussian, nunca como fondo */
    val greenLight = Color(0xFF00CC2C)
}

/**
 * Roles de color: una instancia por esquema, [BrandColorRoles.light] y [BrandColorRoles.dark].
 * La vigente en la composición sale de [LocalBrandColorRoles] (la provee `BrandTheme`).
 */
@Immutable
class BrandColorRoles(
    /** Rol claro/oscuro. Tokens `color.error-text-on-light` / `color.error-text-on-dark`. */
    val errorText: Color,
    /** Rol claro/oscuro. Tokens `color.success-text-on-light` / `color.success-text-on-dark`. */
    val successText: Color,
    /** Rol claro/oscuro. Tokens `color.destructive-text-on-light` / `color.destructive-text-on-dark`. */
    val destructiveText: Color,
    /** Rol claro/oscuro. Tokens `color.text.on-light` / `color.text.on-dark`. */
    val text: Color,
    /** Rol claro/oscuro. Tokens `color.text.placeholder-on-light` / `color.text.placeholder-on-dark`. */
    val textPlaceholder: Color,
    /** Rol claro/oscuro. Tokens `color.text.muted-on-light` / `color.text.muted-on-dark`. */
    val textMuted: Color,
    /** Rol claro/oscuro. Tokens `color.background.light` / `color.background.dark`. */
    val background: Color,
    /** Rol claro/oscuro. Tokens `color.surface.secondary-on-light` / `color.surface.secondary-on-dark`. */
    val surfaceSecondary: Color,
    /** Rol claro/oscuro. Tokens `color.surface.inverse-on-light` / `color.surface.inverse-on-dark`. */
    val surfaceInverse: Color,
    /** Rol claro/oscuro. Tokens `color.surface.highlight-on-dark`. El token solo define el lado oscuro; en el otro lado vale lo mismo. */
    val surfaceHighlight: Color,
    /** Rol claro/oscuro. Tokens `color.border.default-on-light`. El token solo define el lado claro; en el otro lado vale lo mismo. */
    val borderDefault: Color,
    /** Rol claro/oscuro. Tokens `color.border.recessive-on-dark`. El token solo define el lado oscuro; en el otro lado vale lo mismo. */
    val borderRecessive: Color,
    /** Rol claro/oscuro. Tokens `color.disabled.bg-on-light` / `color.disabled.bg-on-dark`. */
    val disabledBg: Color,
    /** Rol claro/oscuro. Tokens `color.disabled.text-on-light` / `color.disabled.text-on-dark`. */
    val disabledText: Color,
    /** Rol claro/oscuro. Tokens `color.disabled.border-on-light` / `color.disabled.border-on-dark`. */
    val disabledBorder: Color,
    /** Rol claro/oscuro. Tokens `color.icon.secondary-on-light` / `color.icon.secondary-on-dark`. */
    val iconSecondary: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-1` / `color.chart.series-1-on-dark`. */
    val chartSeries1: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-2` / `color.chart.series-2-on-dark`. */
    val chartSeries2: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-3` / `color.chart.series-3-on-dark`. */
    val chartSeries3: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-4` / `color.chart.series-4-on-dark`. */
    val chartSeries4: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-5` / `color.chart.series-5-on-dark`. */
    val chartSeries5: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-6` / `color.chart.series-6-on-dark`. */
    val chartSeries6: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-7` / `color.chart.series-7-on-dark`. */
    val chartSeries7: Color,
    /** Rol claro/oscuro. Tokens `color.chart.series-8` / `color.chart.series-8-on-dark`. */
    val chartSeries8: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-100` / `color.chart.sequential-100-on-dark`. */
    val chartSequential100: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-200` / `color.chart.sequential-200-on-dark`. */
    val chartSequential200: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-300` / `color.chart.sequential-300-on-dark`. */
    val chartSequential300: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-400` / `color.chart.sequential-400-on-dark`. */
    val chartSequential400: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-500` / `color.chart.sequential-500-on-dark`. */
    val chartSequential500: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-600` / `color.chart.sequential-600-on-dark`. */
    val chartSequential600: Color,
    /** Rol claro/oscuro. Tokens `color.chart.sequential-700` / `color.chart.sequential-700-on-dark`. */
    val chartSequential700: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-warm-1` / `color.chart.diverging-warm-1-on-dark`. */
    val chartDivergingWarm1: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-warm-2` / `color.chart.diverging-warm-2-on-dark`. */
    val chartDivergingWarm2: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-warm-3` / `color.chart.diverging-warm-3-on-dark`. */
    val chartDivergingWarm3: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-cool-1` / `color.chart.diverging-cool-1-on-dark`. */
    val chartDivergingCool1: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-cool-2` / `color.chart.diverging-cool-2-on-dark`. */
    val chartDivergingCool2: Color,
    /** Rol claro/oscuro. Tokens `color.chart.diverging-cool-3` / `color.chart.diverging-cool-3-on-dark`. */
    val chartDivergingCool3: Color,
) {
    companion object {
        /** Valores para superficie clara (`-on-light`). */
        val light = BrandColorRoles(
            errorText = Color(0xFFB30000),
            successText = Color(0xFF006616),
            destructiveText = Color(0xFFB30000),
            text = Color(0xFF111E30),
            textPlaceholder = Color(0xFF4A4A4A),
            textMuted = Color(0xFF4A4A4A),
            background = Color(0xFFFFFFFF),
            surfaceSecondary = Color(0xFFF2F2F2),
            surfaceInverse = Color(0xFF4A4A4A),
            surfaceHighlight = Color(0xFF6B6B6B),
            borderDefault = Color(0xFFD0D0D0),
            borderRecessive = Color(0xFF4A4A4A),
            disabledBg = Color(0xFFF2F2F2),
            disabledText = Color(0xFF4A4A4A),
            disabledBorder = Color(0xFFD0D0D0),
            iconSecondary = Color(0xFF6B6B6B),
            chartSeries1 = Color(0xFF1E7FF6),
            chartSeries2 = Color(0xFFF16123),
            chartSeries3 = Color(0xFF27A0AF),
            chartSeries4 = Color(0xFFB29124),
            chartSeries5 = Color(0xFFC62C90),
            chartSeries6 = Color(0xFF7D9D22),
            chartSeries7 = Color(0xFF6332C4),
            chartSeries8 = Color(0xFF28A86B),
            chartSequential100 = Color(0xFFDCE9FC),
            chartSequential200 = Color(0xFFB6D2F8),
            chartSequential300 = Color(0xFF8FBAF5),
            chartSequential400 = Color(0xFF67A1F1),
            chartSequential500 = Color(0xFF3B88EE),
            chartSequential600 = Color(0xFF236AC5),
            chartSequential700 = Color(0xFF164B90),
            chartDivergingWarm1 = Color(0xFFF37F54),
            chartDivergingWarm2 = Color(0xFFD45C2C),
            chartDivergingWarm3 = Color(0xFF9F431F),
            chartDivergingCool1 = Color(0xFF70A6F2),
            chartDivergingCool2 = Color(0xFF3484EE),
            chartDivergingCool3 = Color(0xFF1F61B6),
        )

        /** Valores para superficie oscura (`-on-dark`). */
        val dark = BrandColorRoles(
            errorText = Color(0xFFFF8585),
            successText = Color(0xFF00CC2C),
            destructiveText = Color(0xFFFF8585),
            text = Color(0xFFFFFFFF),
            textPlaceholder = Color(0xFFD0D0D0),
            textMuted = Color(0xFFD0D0D0),
            background = Color(0xFF111E30),
            surfaceSecondary = Color(0xFF4A4A4A),
            surfaceInverse = Color(0xFFF2F2F2),
            surfaceHighlight = Color(0xFF6B6B6B),
            borderDefault = Color(0xFFD0D0D0),
            borderRecessive = Color(0xFF4A4A4A),
            disabledBg = Color(0xFF4A4A4A),
            disabledText = Color(0xFFD0D0D0),
            disabledBorder = Color(0xFF6B6B6B),
            iconSecondary = Color(0xFFD0D0D0),
            chartSeries1 = Color(0xFF1D7CF0),
            chartSeries2 = Color(0xFFED5F22),
            chartSeries3 = Color(0xFF28A4B2),
            chartSeries4 = Color(0xFF93771C),
            chartSeries5 = Color(0xFFD840A0),
            chartSeries6 = Color(0xFF7FA123),
            chartSeries7 = Color(0xFF875EF0),
            chartSeries8 = Color(0xFF29AC6D),
            chartSequential100 = Color(0xFF0E376B),
            chartSequential200 = Color(0xFF164B90),
            chartSequential300 = Color(0xFF1F61B6),
            chartSequential400 = Color(0xFF2978DE),
            chartSequential500 = Color(0xFF4E92EF),
            chartSequential600 = Color(0xFF80B0F3),
            chartSequential700 = Color(0xFFB8D3F8),
            chartDivergingWarm1 = Color(0xFFB54E24),
            chartDivergingWarm2 = Color(0xFFE26330),
            chartDivergingWarm3 = Color(0xFFF48F6A),
            chartDivergingCool1 = Color(0xFF256FCF),
            chartDivergingCool2 = Color(0xFF488FEF),
            chartDivergingCool3 = Color(0xFF80B0F3),
        )
    }
}

/** Los roles de color del esquema vigente. Por defecto, el claro. */
val LocalBrandColorRoles = staticCompositionLocalOf { BrandColorRoles.light }

/** Escala de espaciado (`spacing.*`). */
object BrandSpacing {
    /** Token `spacing.1` — 4px — dentro de un control: icono y texto, padding de un badge */
    val s1 = 4.dp
    /** Token `spacing.2` — 8px — dentro de un control: padding de botones y campos, gap entre iconos */
    val s2 = 8.dp
    /** Token `spacing.3` — 12px — entre elementos de un componente: filas de una lista, cabecera y cuerpo */
    val s3 = 12.dp
    /** Token `spacing.4` — 16px — entre elementos de un componente; padding estándar de tarjetas y secciones */
    val s4 = 16.dp
    /** Token `spacing.5` — 24px — entre componentes */
    val s5 = 24.dp
    /** Token `spacing.6` — 32px — entre componentes; bloques de una página */
    val s6 = 32.dp
    /** Token `spacing.7` — 48px — entre secciones */
    val s7 = 48.dp
    /** Token `spacing.8` — 64px — entre secciones destacadas */
    val s8 = 64.dp
}

/** Radios de esquina (`border-radius.*`). */
object BrandRadius {
    /** Token `border-radius.none` — Escala. Valor del rol default */
    val none = 0.dp
    /** Token `border-radius.sm` — Escala. El sistema no lo usa */
    val sm = 4.dp
    /** Token `border-radius.md` — Escala. El sistema no lo usa */
    val md = 8.dp
    /** Token `border-radius.lg` — Escala. El sistema no lo usa */
    val lg = 12.dp
    /** Token `border-radius.xl` — Escala. El sistema no lo usa */
    val xl = 16.dp
    /** Token `border-radius.full` — Escala. Valor del rol round */
    val full = 9999.dp
    /** Token `border-radius.default` — Rol: toda esquina del sistema es recta. Los componentes apuntan aquí, nunca a la escala */
    val default = 0.dp
    /** Token `border-radius.round` — Rol: píldoras y círculos — avatar, tag, badge, interruptor, botón píldora */
    val round = 9999.dp
}

/** Anchos de borde (`border-width.*`). */
object BrandBorderWidth {
    /** Token `border-width.sm` — Escala. Valor del rol default */
    val sm = 1.dp
    /** Token `border-width.md` — Escala. Valor del rol focus */
    val md = 2.dp
    /** Token `border-width.default` — Rol: todo borde del sistema. Los componentes apuntan aquí, nunca a la escala */
    val default = 1.dp
    /** Token `border-width.focus` — Rol: anillo de foco, ancho y separación. Solo para outline; nunca como borde */
    val focus = 2.dp
}

/** Tallas de control y objetivo táctil mínimo (`size-component.*`, `size-target.*`). */
object BrandSize {
    /** Token `size-component.sm` — 32px — talla mínima del sistema: controles compactos, avatares, iconos-botón, logos en barras */
    val componentSm = 32.dp
    /** Token `size-component.md` — 40px — talla por defecto de todo control de una línea: campos, selects, botones */
    val componentMd = 40.dp
    /** Token `size-component.lg` — 48px — controles destacados y objetivo táctil holgado */
    val componentLg = 48.dp
    /** Token `size-target.min` — 24px — objetivo de puntero mínimo (WCAG 2.5.8, nivel AA). No es una talla de maqueta: es el área sensible que un control pequeño (checkbox, radio) extiende de forma invisible más allá de su dibujo */
    val targetMin = 24.dp
}

/** Escala de opacidad (`opacity.*`). */
object BrandOpacity {
    /** Token `opacity.full` — Extremo alto de una transición de opacidad: plenamente presente */
    val full = 1f
    /** Token `opacity.muted` — Presente pero en segundo plano: un control secundario en reposo */
    val muted = 0.7f
    /** Token `opacity.overlay` — Velo bajo un modal o una hoja: oscurece la página sin ocultarla */
    val overlay = 0.6f
    /** Token `opacity.disabled` — Controles deshabilitados: el elemento sigue ahí, atenuado */
    val disabled = 0.4f
}

/** Nombres de familia tipográfica (`font-family.*`), sin la pila de respaldo. Las `FontFamily` de Compose están en `BrandFontFamily`. */
object BrandFontFamilyName {
    /** Token `font-family.sans` — Familia principal: interfaz y texto. Variable (peso 1-1000, tamaño óptico 6-144) */
    val sans = "Google Sans Flex"
    /** Token `font-family.mono` — Código, valores técnicos y contenido preformateado */
    val mono = "Google Sans Code"
    /** Token `font-family.serif` — Excepción de producto: no la usa ningún componente del sistema. Reservada para piezas editoriales o de marca que un producto decida tratar en serif */
    val serif = "Libre Bodoni"
}

/** Escala de tamaños de fuente (`font-size.*`). */
object BrandFontSize {
    /** Token `font-size.0` — 12px — solo cifras dentro de marcas (contadores); nunca texto */
    val s0 = 12.sp
    /** Token `font-size.1` — 14px — etiquetas de interfaz, texto pequeño */
    val s1 = 14.sp
    /** Token `font-size.2` — 1rem (16px) — Body base */
    val s2 = 16.sp
    /** Token `font-size.3` — 1.25rem (20px) — Small subtitles */
    val s3 = 20.sp
    /** Token `font-size.4` — 1.5rem (24px) — Subtitles */
    val s4 = 24.sp
    /** Token `font-size.5` — 1.75rem (28px) — Small titles */
    val s5 = 28.sp
    /** Token `font-size.6` — 2rem (32px) — Titles */
    val s6 = 32.sp
    /** Token `font-size.7` — 2.5rem (40px) — Large titles */
    val s7 = 40.sp
    /** Token `font-size.8` — 3.5rem (56px) — Small display */
    val s8 = 56.sp
    /** Token `font-size.9` — 4.5rem (72px) — Display */
    val s9 = 72.sp
    /** Token `font-size.10` — 6rem (96px) — Large display */
    val s10 = 96.sp
}

/** Pesos de la fuente variable (`font-weight.*`). */
object BrandFontWeight {
    /** Token `font-weight.thin` — Escala de la fuente variable. El sistema no lo usa */
    val thin = FontWeight(100)
    /** Token `font-weight.extralight` — Escala de la fuente variable. El sistema no lo usa */
    val extralight = FontWeight(200)
    /** Token `font-weight.light` — Cuerpo de texto (rol default) */
    val light = FontWeight(300)
    /** Token `font-weight.regular` — Escala de la fuente variable. El sistema no lo usa */
    val regular = FontWeight(400)
    /** Token `font-weight.medium` — Títulos y énfasis (rol emphasis) */
    val medium = FontWeight(500)
    /** Token `font-weight.semibold` — Escala de la fuente variable. El sistema no lo usa */
    val semibold = FontWeight(600)
    /** Token `font-weight.bold` — Escala de la fuente variable. El sistema no lo usa */
    val bold = FontWeight(700)
    /** Token `font-weight.extrabold` — Escala de la fuente variable. El sistema no lo usa */
    val extrabold = FontWeight(800)
    /** Token `font-weight.black` — Escala de la fuente variable. El sistema no lo usa */
    val black = FontWeight(900)
    /** Token `font-weight.default` — Rol: cuerpo de texto. Los componentes apuntan aquí, nunca a la escala */
    val default = FontWeight(300)
    /** Token `font-weight.emphasis` — Rol: títulos, énfasis local (strong, cifras destacadas), etiquetas. Dobla el trazo del cuerpo a 16px */
    val emphasis = FontWeight(500)
}

/** Interlineado como múltiplo del tamaño (`line-height.*`). */
object BrandLineHeight {
    /** Token `line-height.none` — Single line elements, icons */
    val none = 1f
    /** Token `line-height.tight` — Display, large headings */
    val tight = 1.1f
    /** Token `line-height.snug` — Medium headings */
    val snug = 1.3f
    /** Token `line-height.normal` — Body text */
    val normal = 1.5f
    /** Token `line-height.relaxed` — 1,65 — lectura larga */
    val relaxed = 1.65f
}

/** Tracking como fracción del tamaño de fuente (`letter-spacing.*`). */
object BrandLetterSpacing {
    /** Token `letter-spacing.tight` — -0,02em — display y títulos grandes */
    val tight = -0.02.em
    /** Token `letter-spacing.normal` — Body text */
    val normal = 0.em
    /** Token `letter-spacing.wide` — Uppercase labels */
    val wide = 0.05.em
}

/** Una sombra de CSS: desplazamiento, desenfoque y color. */
@Immutable
class BrandShadow(val x: Dp, val y: Dp, val blur: Dp, val color: Color) {
    companion object {
        /** Sin sombra. */
        val None = BrandShadow(0.dp, 0.dp, 0.dp, Color.Transparent)
    }
}

/** Sombras (`shadow.*`). */
object BrandShadows {
    /** Token `shadow.none` — Escala. Valor del rol default */
    val none = BrandShadow.None
    /** Token `shadow.sm` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.08 (sale como rgba(17,30,48,0.08)) */
    val sm = BrandShadow(0.dp, 1.dp, 2.dp, Color(0x14111E30))
    /** Token `shadow.md` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.10 (sale como rgba(17,30,48,0.10)) */
    val md = BrandShadow(0.dp, 2.dp, 8.dp, Color(0x1A111E30))
    /** Token `shadow.lg` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.12 (sale como rgba(17,30,48,0.12)) */
    val lg = BrandShadow(0.dp, 4.dp, 16.dp, Color(0x1F111E30))
    /** Token `shadow.xl` — Escala. El sistema no lo usa. El color es el prusia de la paleta con opacidad 0.16 (sale como rgba(17,30,48,0.16)) */
    val xl = BrandShadow(0.dp, 8.dp, 32.dp, Color(0x29111E30))
    /** Token `shadow.default` — Rol: ningún elemento del sistema proyecta sombra. La elevación se expresa con borde y con el fondo del panel */
    val default = BrandShadow.None
}

/** Duraciones de movimiento, en milisegundos (`motion.duration.*`). */
object BrandDuration {
    /** Token `motion.duration.instant` — Sin transición: cambios que deben ser inmediatos */
    val instant = 0
    /** Token `motion.duration.fast` — Respuesta a la interacción: hover, foco, pulsación */
    val fast = 150
    /** Token `motion.duration.base` — Cambios de estado: abrir un menú, mostrar un tooltip */
    val base = 250
    /** Token `motion.duration.slow` — Cambios de contexto: modales, hojas, paneles que entran */
    val slow = 400
}

/** Curvas de movimiento (`motion.easing.*`). */
object BrandEasing {
    /** Token `motion.easing.default` — Transiciones de propiedad: color, fondo, opacidad */
    val default: Easing = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1f)
    /** Token `motion.easing.in` — Escala. El sistema no lo usa */
    val `in`: Easing = CubicBezierEasing(0.42f, 0f, 1f, 1f)
    /** Token `motion.easing.out` — Salidas: lo que desaparece frena al final */
    val out: Easing = CubicBezierEasing(0f, 0f, 0.58f, 1f)
    /** Token `motion.easing.in-out` — Movimiento: paneles y hojas que se desplazan */
    val inOut: Easing = CubicBezierEasing(0.42f, 0f, 0.58f, 1f)
    /** Token `motion.easing.linear` — Escala. El sistema no lo usa */
    val linear: Easing = LinearEasing
}
